FPAttributeValueFile

n  SubType="IVI" 

n  SubVersion="1" 

v attrAcMaxFreqRangeTable DataType="d" 
 300000.0 (3.00000000000000E+5)
  ""


v attrAcMinFreqRangeTable DataType="d" 
 200.0 (2.00000000000000E+2)
  ""

 20.0 (2.00000000000000E+1)
  ""

 3.0 (3.00000000000000E+0)
  ""


v attrActualRangeTable DataType="d" 
 AG3446X_VAL_DC_VOLTS (1.00000000000000E+0)
  "DC Volts"

 AG3446X_VAL_AC_VOLTS (2.00000000000000E+0)
  "AC Volts"

 AG3446X_VAL_DC_VOLTS_RATIO (1.00300000000000E+3)
  "DC Volts Ratio"

 AG3446X_VAL_DC_CURRENT (3.00000000000000E+0)
  "DC Current"

 AG3446X_VAL_AC_CURRENT (4.00000000000000E+0)
  "AC Current"

 AG3446X_VAL_2_WIRE_RES (5.00000000000000E+0)
  "2 Wire Resistance"

 AG3446X_VAL_4_WIRE_RES (1.01000000000000E+2)
  "4 Wire Resistance"


v attrApertureTimeNplc34465DigRangeTable DataType="d" 
 0.001 (1.00000000000000E-3)
  ""

 0.002 (2.00000000000000E-3)
  ""

 0.006 (6.00000000000000E-3)
  ""

 0.02 (2.00000000000000E-2)
  ""

 0.06 (6.00000000000000E-2)
  ""

 0.2 (2.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""


v attrApertureTimeNplc34465RangeTable DataType="d" 
 0.02 (2.00000000000000E-2)
  ""

 0.06 (6.00000000000000E-2)
  ""

 0.2 (2.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""


v attrApertureTimeNplcRangeTable DataType="d" 
 0.02 (2.00000000000000E-2)
  ""

 0.2 (2.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""


v attrApertureTimeSeconds34465FreqRangeTable DataType="d" 
 0.001 (1.00000000000000E-3)
  ""

 0.01 (1.00000000000000E-2)
  ""

 0.1 (1.00000000000000E-1)
  ""

 1 (1.00000000000000E+0)
  ""


v attrApertureTimeSecondsEDU34450AFreqRangeTable DataType="d" 
 1 (1.00000000000000E+0)
  ""


v attrApertureTimeSecondsFreqRangeTable DataType="d" 
 0.01 (1.00000000000000E-2)
  ""

 0.1 (1.00000000000000E-1)
  ""

 1 (1.00000000000000E+0)
  ""


v attrApertureTimeUnitsRangeTable DataType="i" 
 AG3446X_VAL_SECONDS (0)
  "Seconds"

 AG3446X_VAL_POWER_LINE_CYCLES (1)
  "Power Line Cycles"


v attrAutoZeroRangeTable DataType="i" 
 AG3446X_VAL_AUTO_ZERO_OFF (0)
  "Disables the DMM from taking any more Zero Readings.  The DMM subtract "
  "the last Zero Reading from all subsequent values it measures."

 AG3446X_VAL_AUTO_ZERO_ON (1)
  "Configures the DMM to take a Zero Reading for each measurement.  The DMM "
  "subtracts the Zero Reading from the value it measures."

 AG3446X_VAL_AUTO_ZERO_ONCE (2)
  "Configures the DMM to take a Zero Reading immediately.  The DMM then "
  "subtracts this Zero Reading from all subsequent values it measures."


v attrConfMeasEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_CONF_MEAS_CONT (1.00000000000000E+0)
  "continuity"

 AG3446X_VAL_CONF_MEAS_AC_CURRENT (2.00000000000000E+0)
  "Ac Current"

 AG3446X_VAL_CONF_MEAS_DC_CURRENT (3.00000000000000E+0)
  "DC Current"

 AG3446X_VAL_CONF_MEAS_DIODE (4.00000000000000E+0)
  "Diode"

 AG3446X_VAL_CONF_MEAS_FREQ (5.00000000000000E+0)
  "Frequency"

 AG3446X_VAL_CONF_MEAS_RES (7.00000000000000E+0)
  "2 wire Resistance"

 AG3446X_VAL_CONF_MEAS_FRES (8.00000000000000E+0)
  "4 wire Resistance"

 AG3446X_VAL_CONF_MEAS_TEMP (9.00000000000000E+0)
  "Temperature"

 AG3446X_VAL_CONF_MEAS_AC_VOLTAGE (1.00000000000000E+1)
  "AC voltage"

 AG3446X_VAL_CONF_MEAS_DC_VOLTAGE (1.10000000000000E+1)
  "DC voltage"

 AG3446X_VAL_CONF_MEAS_CAP (1.30000000000000E+1)
  "Capacitance"


v attrConfMeasRangeTable DataType="i" 
 AG3446X_VAL_CONF_MEAS_CONT (1)
  "Continuity"

 AG3446X_VAL_CONF_MEAS_AC_CURRENT (2)
  "AC Current"

 AG3446X_VAL_CONF_MEAS_DC_CURRENT (3)
  "DC Current"

 AG3446X_VAL_CONF_MEAS_DIODE (4)
  "Diode"

 AG3446X_VAL_CONF_MEAS_FREQ (5)
  "Frequency"

 AG3446X_VAL_CONF_MEAS_PER (6)
  "Period"

 AG3446X_VAL_CONF_MEAS_RES (7)
  "2 Wire Resistance"

 AG3446X_VAL_CONF_MEAS_FRES (8)
  "4 Wire Resistance"

 AG3446X_VAL_CONF_MEAS_TEMP (9)
  "Temperature"

 AG3446X_VAL_CONF_MEAS_AC_VOLTAGE (10)
  "AC Voltage"

 AG3446X_VAL_CONF_MEAS_DC_VOLTAGE (11)
  "DC Voltage"

 AG3446X_VAL_CONF_MEAS_DC_VOLTAGE_RATIO (12)
  "DC Voltage Ratio"

 AG3446X_VAL_CONF_MEAS_CAP (13)
  "Capacitance"


v attrCurrentTerminalRangeTable DataType="i" 
 AG3446X_VAL_CURR_TERM_3 (3)
  "3A terminals"

 AG3446X_VAL_CURR_TERM_10 (10)
  "10A terminals"


v attrEDU34450ADbmReferenceRangeTable DataType="d" 
 AG3446X_VAL_2 (2.00000000000000E+0)
  "dBm reference resistance"

 AG3446X_VAL_4 (4.00000000000000E+0)
  "dBm reference resistance"

 AG3446X_VAL_8 (8.00000000000000E+0)
  "dBm reference resistance"

 AG3446X_VAL_16 (1.60000000000000E+1)
  "dBm reference resistance"

 AG3446X_VAL_50 (5.00000000000000E+1)
  "dBm reference resistance"

 AG3446X_VAL_75 (7.50000000000000E+1)
  "dBm reference resistance"

 AG3446X_VAL_93 (9.30000000000000E+1)
  "dBm reference resistance"

 AG3446X_VAL_110 (1.10000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_124 (1.24000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_125 (1.25000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_135 (1.35000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_150 (1.50000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_250 (2.50000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_300 (3.00000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_500 (5.00000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_600 (6.00000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_800 (8.00000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_900 (9.00000000000000E+2)
  "dBm reference resistance"

 AG3446X_VAL_1000 (1.00000000000000E+3)
  "dBm reference resistance"

 AG3446X_VAL_1200 (1.20000000000000E+3)
  "dBm reference resistance"

 AG3446X_VAL_8000 (8.00000000000000E+3)
  "dBm reference resistance"


v attrEDU34450AFunctionRangeTable DataType="i" 
 AG3446X_VAL_DC_VOLTS (1)
  "DC Volts"

 AG3446X_VAL_AC_VOLTS (2)
  "AC Volts"

 AG3446X_VAL_DC_CURRENT (3)
  "DC Current"

 AG3446X_VAL_AC_CURRENT (4)
  "AC Current"

 AG3446X_VAL_2_WIRE_RES (5)
  "2 Wire Resistance"

 AG3446X_VAL_4_WIRE_RES (101)
  "4 Wire Resistance"

 AG3446X_VAL_FREQ (104)
  "Frequency"

 AG3446X_VAL_TEMPERATURE (108)
  "Temperature (C)"

 AG3446X_VAL_CONTINUITY (1001)
  "Continuity"

 AG3446X_VAL_DIODE (1002)
  "Diode"

 AG3446X_VAL_CAPACITANCE (1004)
  "Capacitance"


v attrFreqVoltageRangeEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables voltage auto ranging for primary frequency measurements."

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables voltage auto ranging for primary frequency measurements."

 1.0 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""

 750.0 (7.50000000000000E+2)
  ""


v attrFreqVoltageRangeRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Auto range on"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Auto range off"

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Auto range once"

 0.1 (1.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""

 1000.0 (1.00000000000000E+3)
  ""


v attrFunctionRangeTable DataType="i" 
 AG3446X_VAL_DC_VOLTS (1)
  "DC Volts"

 AG3446X_VAL_AC_VOLTS (2)
  "AC Volts"

 AG3446X_VAL_DC_CURRENT (3)
  "DC Current"

 AG3446X_VAL_AC_CURRENT (4)
  "AC Current"

 AG3446X_VAL_2_WIRE_RES (5)
  "2 Wire Resistance"

 AG3446X_VAL_4_WIRE_RES (101)
  "4 Wire Resistance"

 AG3446X_VAL_FREQ (104)
  "Frequency"

 AG3446X_VAL_PERIOD (105)
  "Period"

 AG3446X_VAL_TEMPERATURE (108)
  "Temperature (C)"

 AG3446X_VAL_CONTINUITY (1001)
  "Continuity"

 AG3446X_VAL_DIODE (1002)
  "Diode"

 AG3446X_VAL_DC_VOLTS_RATIO (1003)
  "DC Voltage Ratio"

 AG3446X_VAL_CAPACITANCE (1004)
  "Capacitance"


v attrHistPointRangeTable DataType="i" 
 AG3446X_VAL_10 (10)
  "10 bins"

 AG3446X_VAL_20 (20)
  "20 bins"

 AG3446X_VAL_40 (40)
  "40 bins"

 AG3446X_VAL_100 (100)
  "100 bins"

 AG3446X_VAL_200 (200)
  "200 bins"

 AG3446X_VAL_400 (400)
  "400 bins"


v attrMemFormReadingSeparatorRangeTable DataType="i" 
 AG3446X_VAL_SEPARATOR_COM (1)
  "Comma"

 AG3446X_VAL_SEPARATOR_SEM (2)
  "Semicolon"

 AG3446X_VAL_SEPARATOR_TAB (3)
  "Tab"


v attrModel DataType="i" 
 AG3446X_VAL_MODEL_34460A (60)
  "34460A"

 AG3446X_VAL_MODEL_34461A (61)
  "34461A"

 AG3446X_VAL_MODEL_34465A (65)
  "34465A"

 AG3446X_VAL_MODEL_34470A (70)
  "34470A"

 AG3446X_VAL_MODEL_EDU34450A (50)
  "EDU34450A"


v attrRangeACVoltageEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 1 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""

 750.0 (7.50000000000000E+2)
  ""


v attrRangeCapacitanceEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 1e-8 (1.00000000000000E-8)
  ""

 1e-7 (1.00000000000000E-7)
  ""

 1e-6 (1.00000000000000E-6)
  ""

 1e-5 (1.00000000000000E-5)
  ""

 1e-4 (1.00000000000000E-4)
  ""

 1e-3 (1.00000000000000E-3)
  ""

 1e-2 (1.00000000000000E-2)
  ""


v attrRangeCapacitanceRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Performs an immediate autorange"

 1e-9 (1.00000000000000E-9)
  ""

 1e-8 (1.00000000000000E-8)
  ""

 1e-7 (1.00000000000000E-7)
  ""

 1e-6 (1.00000000000000E-6)
  ""

 1e-5 (1.00000000000000E-5)
  ""

 1e-4 (1.00000000000000E-4)
  ""


v attrRangeChangeModeRangeTable DataType="i" 
 AG3446X_VAL_RANGE_CHANGE_FAST (1)
  "Fast"

 AG3446X_VAL_RANGE_CHANGE_CONT (2)
  "Continuous"


v attrRangeCurrentEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 0.1 (1.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 3.0 (3.00000000000000E+0)
  ""


v attrRangeCurrentRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Auto range on"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Auto range off"

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Auto range once"

 0.0001 (1.00000000000000E-4)
  ""

 0.001 (1.00000000000000E-3)
  ""

 0.01 (1.00000000000000E-2)
  ""

 0.1 (1.00000000000000E-1)
  ""

 1.0 (1.00000000000000E+0)
  ""

 3.0 (3.00000000000000E+0)
  ""


v attrRangeDCVoltageEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 1 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""

 1000.0 (1.00000000000000E+3)
  ""


v attrRangeDefaultRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Auto range on"


v attrRangeResistanceEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto range"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto range"

 1000.0 (1.00000000000000E+3)
  ""

 10000.0 (1.00000000000000E+4)
  ""

 100000.0 (1.00000000000000E+5)
  ""

 1000000.0 (1.00000000000000E+6)
  ""

 10000000.0 (1.00000000000000E+7)
  ""

 100000000.0 (1.00000000000000E+8)
  ""


v attrRangeResistanceRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Auto range on"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Auto range off"

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Auto range once"

 100.0 (1.00000000000000E+2)
  ""

 1000.0 (1.00000000000000E+3)
  ""

 10000.0 (1.00000000000000E+4)
  ""

 100000.0 (1.00000000000000E+5)
  ""

 1000000.0 (1.00000000000000E+6)
  ""

 10000000.0 (1.00000000000000E+7)
  ""

 100000000.0 (1.00000000000000E+8)
  ""


v attrRangeVoltageRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Auto range on"

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Auto range off"

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Auto range once"

 0.1 (1.00000000000000E-1)
  ""

 1 (1.00000000000000E+0)
  ""

 10.0 (1.00000000000000E+1)
  ""

 100.0 (1.00000000000000E+2)
  ""

 1000.0 (1.00000000000000E+3)
  ""


v attrResolution34460RangeTable DataType="d" 
 .0001 (1.00000000000000E-4)
  ""

 .00003 (3.00000000000000E-5)
  ""

 .00001 (1.00000000000000E-5)
  ""

 .000003 (3.00000000000000E-6)
  ""


v attrResolution34461RangeTable DataType="d" 
 .00001 (1.00000000000000E-5)
  ""

 .000003 (3.00000000000000E-6)
  ""

 .000001 (1.00000000000000E-6)
  ""

 .0000003 (3.00000000000000E-7)
  ""


v attrResolution34465RangeTable DataType="d" 
 0.000015 (1.50000000000000E-5)
  ""

 0.000006 (6.00000000000000E-6)
  ""

 0.000003 (3.00000000000000E-6)
  ""

 0.0000015 (1.50000000000000E-6)
  ""

 0.0000007 (7.00000000000000E-7)
  ""

 0.0000003 (3.00000000000000E-7)
  ""

 0.0000001 (1.00000000000000E-7)
  ""

 0.00000003 (3.00000000000000E-8)
  ""


v attrResolution34470RangeTable DataType="d" 
 0.00001 (1.00000000000000E-5)
  ""

 0.000003 (3.00000000000000E-6)
  ""

 0.000001 (1.00000000000000E-6)
  ""

 0.0000005 (5.00000000000000E-7)
  ""

 0.0000003 (3.00000000000000E-7)
  ""

 0.0000001 (1.00000000000000E-7)
  ""

 0.00000003 (3.00000000000000E-8)
  ""

 0.00000001 (1.00000000000000E-8)
  ""


v attrResolutionEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_SLOW (1.00000000000000E+0)
  "Slow"

 AG3446X_VAL_MEDIUM (2.00000000000000E+0)
  "Medium"

 AG3446X_VAL_FAST (3.00000000000000E+0)
  "Fast"


v attrSampleTriggerRangeTable DataType="i" 
 AG3446X_VAL_IMMEDIATE (1)
  "Immediate"

 AG3446X_VAL_TIMER (1001)
  "Timer"


v attrScaleDbmReferenceRangeTable DataType="d" 
 AG3446X_VAL_50 (5.00000000000000E+1)
  "Reference resistance of 50 ohm"

 AG3446X_VAL_75 (7.50000000000000E+1)
  "Reference resistance of 75 ohm"

 AG3446X_VAL_93 (9.30000000000000E+1)
  "Reference resistance of 93 ohm"

 AG3446X_VAL_110 (1.10000000000000E+2)
  "Reference resistance of 110 ohm"

 AG3446X_VAL_124 (1.24000000000000E+2)
  "Reference resistance of 124 ohm"

 AG3446X_VAL_125 (1.25000000000000E+2)
  "Reference resistance of 125 ohm"

 AG3446X_VAL_135 (1.35000000000000E+2)
  "Reference resistance of 135 ohm"

 AG3446X_VAL_150 (1.50000000000000E+2)
  "Reference resistance of 150 ohm"

 AG3446X_VAL_250 (2.50000000000000E+2)
  "Reference resistance of 250 ohm"

 AG3446X_VAL_300 (3.00000000000000E+2)
  "Reference resistance of 300 ohm"

 AG3446X_VAL_500 (5.00000000000000E+2)
  "Reference resistance of 500 ohm"

 AG3446X_VAL_600 (6.00000000000000E+2)
  "Reference resistance of 600 ohm"

 AG3446X_VAL_800 (8.00000000000000E+2)
  "Reference resistance of 800 ohm"

 AG3446X_VAL_900 (9.00000000000000E+2)
  "Reference resistance of 900 ohm"

 AG3446X_VAL_1000 (1.00000000000000E+3)
  "Reference resistance of 1000 ohm"

 AG3446X_VAL_1200 (1.20000000000000E+3)
  "Reference resistance of 1200 ohm"

 AG3446X_VAL_8000 (8.00000000000000E+3)
  "Reference resistance of 8000 ohm"


v attrScaleFunction34465RangeTable DataType="d" 
 AG3446X_VAL_SCALE_FUNC_DB (1.00000000000000E+0)
  "DB"

 AG3446X_VAL_SCALE_FUNC_DBM (2.00000000000000E+0)
  "DBM"

 AG3446X_VAL_SCALE_FUNC_PCT (3.00000000000000E+0)
  "Percent change"

 AG3446X_VAL_SCALE_FUNC_SCAL (4.00000000000000E+0)
  "Scale"


v attrScaleFunctionRangeTable DataType="i" 
 AG3446X_VAL_SCALE_FUNC_DB (1)
  "Performs a relative dB computation"

 AG3446X_VAL_SCALE_FUNC_DBM (2)
  "Performs a relative dBM computation"


v attrSecFuncCacRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_FREQ (8)
  "Frequency"

 AG3446X_VAL_SEC_FUNC_CDC (5)
  "DC Current"


v attrSecFuncCapacitanceRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"


v attrSecFuncCdcRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Caltulate Data"

 AG3446X_VAL_SEC_FUNC_CAC (6)
  "AC Current"

 AG3446X_VAL_SEC_FUNC_PTP (9)
  "Peak to Peak"


v attrSecFuncDcRatioRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_SENS (10)
  "Sense Data"


v attrSecFuncFreqRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_PER (7)
  "Period"

 AG3446X_VAL_SEC_FUNC_VAC (4)
  "AC Voltage"


v attrSecFuncPerRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_FREQ (8)
  "Frequency"

 AG3446X_VAL_SEC_FUNC_VAC (4)
  "AC Volts"


v attrSecFuncResRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"


v attrSecFuncTempRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_SENS (10)
  "Sense Data"


v attrSecFuncVacRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_VDC (3)
  "DC Volts"


v attrSecFuncVdcRangeTable DataType="i" 
 AG3446X_VAL_SEC_FUNC_OFF (1)
  "Off"

 AG3446X_VAL_SEC_FUNC_CALC (2)
  "Calculate Data"

 AG3446X_VAL_SEC_FUNC_VAC (4)
  "AC Volts"

 AG3446X_VAL_SEC_FUNC_PTP (9)
  "Peak to Peak"


v attrSmoothingResponseRangeTable DataType="i" 
 AG3446X_VAL_SMOOTHING_RESPONSE_SLOW (1)
  "Slow, 100 measurements"

 AG3446X_VAL_SMOOTHING_RESPONSE_MEDIUM (2)
  "Medium, 50 measurements"

 AG3446X_VAL_SMOOTHING_RESPONSE_FAST (3)
  "Fast, 10 measurements"


v attrTempTcRefJuncTypeRangeTable DataType="i" 
 AG3446X_VAL_TEMP_REF_JUNC_INTERNAL (1)
  "Internal"

 AG3446X_VAL_TEMP_REF_JUNC_FIXED (2)
  "Fixed"


v attrTempTcTypeRangeTable DataType="i" 
 AG3446X_VAL_TEMP_TC_E (4)
  "E-type thermocouple measurements"

 AG3446X_VAL_TEMP_TC_J (6)
  "J-type thermocouple measurements"

 AG3446X_VAL_TEMP_TC_K (7)
  "K-type thermocouple measurements"

 AG3446X_VAL_TEMP_TC_N (8)
  "N-type thermocouple measurements"

 AG3446X_VAL_TEMP_TC_R (9)
  "R-type thermocouple measurements"

 AG3446X_VAL_TEMP_TC_T (11)
  "T-type thermocouple measurements"


v attrTempTransducerTypeRangeTable DataType="i" 
 AG3446X_VAL_THERMOCOUPLE (1)
  "Thermocouple"

 AG3446X_VAL_2_WIRE_RTD (3)
  "2 Wire RTD"

 AG3446X_VAL_4_WIRE_RTD (4)
  "4 Wire RTD"

 AG3446X_VAL_2_WIRE_THER (2)
  "2 Wire Thermistor"

 AG3446X_VAL_4_WIRE_THER (1001)
  "4 Wire Thermistor"


v attrTriggerSlopeRangeTable DataType="i" 
 AG3446X_VAL_POSITIVE (0)
  "Positive slope"

 AG3446X_VAL_NEGATIVE (1)
  "Negative slope"


v attrTriggerSource34465RangeTable DataType="i" 
 AG3446X_VAL_IMMEDIATE (1)
  "The DMM does not wait for a trigger of any kind."

 AG3446X_VAL_EXTERNAL (2)
  "The DMM waits for a trigger on the external trigger input."

 AG3446X_VAL_SOFTWARE_TRIG (3)
  "The DMM waits until you call the ag3446x_SendSoftwareTrigger function."

 AG3446X_VAL_INTERNAL (1002)
  "Provides level triggering capability."


v attrTriggerSourceEDU344520ARangeTable DataType="i" 
 AG3446X_VAL_IMMEDIATE (1)
  "The DMM does not wait for a trigger of any kind."

 AG3446X_VAL_SOFTWARE_TRIG (3)
  "The DMM waits until you call the ag3446x_SendSoftwareTrigger function."


v attrTriggerSourceRangeTable DataType="i" 
 AG3446X_VAL_IMMEDIATE (1)
  "The DMM does not wait for a trigger of any kind."

 AG3446X_VAL_EXTERNAL (2)
  "The DMM waits for a trigger on the external trigger input."

 AG3446X_VAL_SOFTWARE_TRIG (3)
  "The DMM waits until you call the ag3446x_SendSoftwareTrigger function."


v Boolean_values DataType="i" 
 VI_TRUE (1)
  "True"

 VI_FALSE (0)
  "False"


v attrRangeVoltageEDU34450ARangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Enables auto ranging for primary DC voltage measurements."

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto ranging for primary DC voltage measurements."

 1 (1.00000000000000E+0)
  "Measurement range for primary DC voltage measurements."

 10.0 (1.00000000000000E+1)
  "Measurement range for primary DC voltage measurements."

 100.0 (1.00000000000000E+2)
  "Measurement range for primary DC voltage measurements."

 1000.0 (1.00000000000000E+3)
  "Measurement range for primary DC voltage measurements."


v VDCRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Configures the DMM to calculate the range before each measurement "
  "automatically. "

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto-ranging.  The DMM sets the range to the value it most "
  "recently calculated."

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Configures the DMM to calculate the range before the next measurement.  "
  "The DMM uses this range value for all subsequent measurements."


v VACRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Configures the DMM to calculate the range before each measurement "
  "automatically. "

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto-ranging.  The DMM sets the range to the value it most "
  "recently calculated."

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Configures the DMM to calculate the range before the next measurement.  "
  "The DMM uses this range value for all subsequent measurements."


v ohmsRangeTable DataType="d" 
 AG3446X_VAL_AUTO_RANGE_ON (-1.00000000000000E+0)
  "Configures the DMM to calculate the range before each measurement "
  "automatically. "

 AG3446X_VAL_AUTO_RANGE_OFF (-2.00000000000000E+0)
  "Disables auto-ranging.  The DMM sets the range to the value it most "
  "recently calculated."

 AG3446X_VAL_AUTO_RANGE_ONCE (-3.00000000000000E+0)
  "Configures the DMM to calculate the range before the next measurement.  "
  "The DMM uses this range value for all subsequent measurements."


v attrTriggerDelayRangeTable DataType="d" 
 AG3446X_VAL_AUTO_DELAY_ON (-1.00000000000000E+0)
  "Configures the DMM to calculate the trigger delay before each measurement."

 AG3446X_VAL_AUTO_DELAY_OFF (-2.00000000000000E+0)
  "Stops the DMM from calculating the trigger delay.  Sets the trigger delay "
  "to the last trigger delay the DMM calculated.\n"


v attrMeasCompleteDestRangeTable DataType="i" 
 AG3446X_VAL_NONE (-1)
  "The DMM does not send the measurement-complete signal."

 AG3446X_VAL_EXTERNAL (2)
  "The DMM sends the measurement-complete signal on the external trigger "
  "line."

 AG3446X_VAL_TTL0 (111)
  "The DMM sends the measurement-complete signal on TTL0 line."

 AG3446X_VAL_TTL1 (112)
  "The DMM sends the measurement-complete signal on TTL1 line."

 AG3446X_VAL_TTL2 (113)
  "The DMM sends the measurement-complete signal on TTL2 line."

 AG3446X_VAL_TTL3 (114)
  "The DMM sends the measurement-complete signal on TTL3 line."

 AG3446X_VAL_TTL4 (115)
  "The DMM sends the measurement-complete signal on TTL4 line."

 AG3446X_VAL_TTL5 (116)
  "The DMM sends the measurement-complete signal on TTL5 line."

 AG3446X_VAL_TTL6 (117)
  "The DMM sends the measurement-complete signal on TTL6 line."

 AG3446X_VAL_TTL7 (118)
  "The DMM sends the measurement-complete signal on TTL7 line."

 AG3446X_VAL_ECL0 (119)
  "The DMM sends the measurement-complete signal on ECL0 line."

 AG3446X_VAL_ECL1 (120)
  "The DMM sends the measurement-complete signal on ECL1 line."

 AG3446X_VAL_PXI_STAR (131)
  "The DMM sends the measurement-complete signal on PXI STAR bus."


v attrResolutionAbsoluteRangeTable DataType="d" 
 .0000001 (1.00000000000000E-7)
  ""

 .000001 (1.00000000000000E-6)
  ""

 .00001 (1.00000000000000E-5)
  ""

 .0001 (1.00000000000000E-4)
  ""

 .001 (1.00000000000000E-3)
  ""

 .01 (1.00000000000000E-2)
  ""

 .1 (1.00000000000000E-1)
  ""


v attrTempRtdAlphaRangeTable DataType="d" 
 0.000385 (3.85000000000000E-4)
  ""

 0.000391 (3.91000000000000E-4)
  ""


0 ag3446x_SetAttributeViInt32 3 4 false s DataType="ViInt32" 
0 ag3446x_GetAttributeViInt32 3 4 false g DataType="ViInt32" 
0 ag3446x_CheckAttributeViInt32 3 4 false s DataType="ViInt32" 
0 ag3446x_SetAttributeViInt64 3 4 false s DataType="ViInt64" 
0 ag3446x_GetAttributeViInt64 3 4 false g DataType="ViInt64" 
0 ag3446x_CheckAttributeViInt64 3 4 false s DataType="ViInt64" 
0 ag3446x_SetAttributeViReal64 3 4 false s DataType="ViReal64" 
0 ag3446x_GetAttributeViReal64 3 4 false g DataType="ViReal64" 
0 ag3446x_CheckAttributeViReal64 3 4 false s DataType="ViReal64" 
0 ag3446x_SetAttributeViSession 3 4 false s DataType="ViSession" 
0 ag3446x_GetAttributeViSession 3 4 false g DataType="ViSession" 
0 ag3446x_CheckAttributeViSession 3 4 false s DataType="ViSession" 
0 ag3446x_SetAttributeViBoolean 3 4 false s DataType="ViBoolean" 
0 ag3446x_GetAttributeViBoolean 3 5 false g DataType="ViBoolean" 
0 ag3446x_CheckAttributeViBoolean 3 4 false s DataType="ViBoolean" 
0 ag3446x_SetAttributeViString 3 4 false s DataType="ViString" 
0 ag3446x_GetAttributeViString 3 4 false g DataType="ViString" 
0 ag3446x_CheckAttributeViString 3 4 false s DataType="ViString" 

1 all "Inherent IVI Attributes" 
 "Attributes common to all IVI instrument drivers."

2 all "User Options" 
 "Attributes you can set to affect the operation of this instrument driver.\n"
 "    "

3 all "Range Check" AG3446X_ATTR_RANGE_CHECK ViBoolean gs Boolean_values 
 "Specifies whether to validate attribute values and function parameters.  "
 "If enabled, the instrument driver validates the parameter values that you "
 "pass to driver functions.  Range checking parameters is very useful for "
 "debugging.  After you validate your program, you can set this attribute to "
 "VI_FALSE to disable range checking and maximize performance.\n"
 "    The default value is VI_TRUE.  Use the ag3446x_InitWithOptions "
 "function to override this value.\n"
 "\n"
 "Attribute Value: 1050002"

3 all "Query Instrument Status" AG3446X_ATTR_QUERY_INSTRUMENT_STATUS ViBoolean gs Boolean_values 
 "Specifies whether the instrument driver queries the instrument status "
 "after each operation.  Querying the instrument status is very useful for "
 "debugging.  After you validate your program, you can set this attribute to "
 "VI_FALSE to disable status checking and maximize performance\n"
 "    The instrument driver can choose to ignore status checking for "
 "particular attributes regardless of the setting of this attribute.\n"
 "    The default value is VI_FALSE.  Use the ag3446x_InitWithOptions "
 "function to override this value.\n"
 "\n"
 "Attribute Value: 1050003"

3 all "Cache" AG3446X_ATTR_CACHE ViBoolean gs Boolean_values 
 "Specifies whether to cache the value of attributes.  When caching is "
 "enabled, the instrument driver keeps track of the current instrument "
 "settings and avoids sending redundant commands to the instrument.  Thus, "
 "you can significantly increase execution speed.\n"
 "    The instrument driver can choose always to cache or never to cache "
 "particular attributes regardless of the setting of this attribute.\n"
 "    The default value is VI_TRUE.  Use the ag3446x_InitWithOptions "
 "function to override this value.\n"
 "\n"
 "Attribute Value: 1050004"

3 all "Simulate" AG3446X_ATTR_SIMULATE ViBoolean gs Boolean_values 
 "Specifies whether or not to simulate instrument driver I/O operations.  If "
 "simulation is enabled, instrument driver functions perform range checking "
 "and call Ivi_GetAttribute and Ivi_SetAttribute functions, but they do not "
 "perform instrument I/O.  For output parameters that represent instrument "
 "data, the instrument driver functions return calculated values.\n"
 "    The default value is VI_FALSE.  Use the ag3446x_InitWithOptions "
 "function to override this value.\n"
 "\n"
 "Attribute Value: 1050005"

3 all "Record Value Coercions" AG3446X_ATTR_RECORD_COERCIONS ViBoolean gs Boolean_values 
 "Specifies whether the IVI engine keeps a list of the value coercions it "
 "makes for integer and real type attributes.  You call ag3446x Get Next "
 "Coercion Record to extract and delete the oldest coercion record from the "
 "list.\n"
 "    The default value is VI_FALSE.  Use the ag3446x_InitWithOptions "
 "function to override this value.\n"
 "\n"
 "Attribute Value: 1050006"

3 all "Interchange Check" AG3446X_ATTR_INTERCHANGE_CHECK ViBoolean gs Boolean_values 
 "Specifies whether to perform interchangeability checking and retrieve "
 "interchangeability warnings.\n"
 "\n"
 "The default value is VI_FALSE.\n"
 "\n"
 "Interchangeability warnings indicate that using your application with a "
 "different instrument might cause different behavior.  You call ag3446x Get "
 "Next Interchange Warning to extract interchange warnings.  Call the "
 "ag3446x_ClearInterchangeWarnings function to clear the list of "
 "interchangeability warnings without reading them.\n"
 "Interchangeability checking logs a warning for each attribute you have not "
 "set that affects the behavior of the instrument.\n"
 "\n"
 "Attribute Value: 1050021"

2 all "Driver Identification" 
 "Attributes that provide identity and version information about this "
 "instrument driver.\n"
 "    "

3 all "Description" AG3446X_ATTR_SPECIFIC_DRIVER_DESCRIPTION ViString g 
 "A string that contains a brief description of the specific driver.\n"
 "\n"
 "Attribute Value: 1050514"

3 all "Driver Prefix" AG3446X_ATTR_SPECIFIC_DRIVER_PREFIX ViString g 
 "A string that contains the prefix for the instrument driver.  The name of "
 "each user-callable function in this driver starts with this prefix.\n"
 "\n"
 "Attribute Value: 1050302"

3 all "Driver Vendor" AG3446X_ATTR_SPECIFIC_DRIVER_VENDOR ViString g 
 "A string that contains the name of the vendor that supplies this driver.\n"
 "\n"
 "Attribute Value: 1050513"

3 all "Revision" AG3446X_ATTR_SPECIFIC_DRIVER_REVISION ViString g 
 "A string that contains additional version information about this "
 "instrument driver.\n"
 "\n"
 "Attribute Value: 1050551"

3 all "Class Specification Major Version" AG3446X_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION ViInt32 g 
 "The major version number of the class specification with which this driver "
 "is compliant.\n"
 "\n"
 "Attribute Value: 1050515"

3 all "Class Specification Minor Version" AG3446X_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION ViInt32 g 
 "The minor version number of the class specification with which this driver "
 "is compliant.\n"
 "\n"
 "Attribute Value: 1050516"

2 all "Driver Capabilities" 
 "Attributes that provide information about the capabilities of this "
 "instrument driver.\n"
 "    "

3 all "Supported Instrument Models" AG3446X_ATTR_SUPPORTED_INSTRUMENT_MODELS ViString g 
 "Contains a model code of the instrument. For drivers that support more "
 "than one device, this attribute contains a comma-separated list of "
 "supported instrument models.\n"
 "\n"
 "Attribute Value: 1050327"

3 all "Class Group Capabilities" AG3446X_ATTR_GROUP_CAPABILITIES ViString g 
 "A string that contains a comma-separated list of class-extension groups "
 "that this driver implements.\n"
 "\n"
 "Attribute Value: 1050401"

2 all "Instrument Identification" 
 "Attributes that provide identity information about the instrument that you "
 "are using.    "

3 all "Manufacturer" AG3446X_ATTR_INSTRUMENT_MANUFACTURER ViString g 
 "A string that contains the name of the instrument manufacturer you are "
 "currently using.\n"
 "\n"
 "Attribute Value: 1050511"

3 all "Model" AG3446X_ATTR_INSTRUMENT_MODEL ViString g 
 "A string that contains the model number or name of the instrument that you "
 "are currently using.\n"
 "\n"
 "Attribute Value: 1050512"

3 all "Firmware Revision" AG3446X_ATTR_INSTRUMENT_FIRMWARE_REVISION ViString g 
 "A string that contains the firmware revision information for the "
 "instrument you are currently using.\n"
 "\n"
 "Attribute Value: 1050510"

2 all "Advanced Session Information" 
 "Attributes that contain additional information concerning the instrument "
 "driver session.      "

3 all "Logical Name" AG3446X_ATTR_LOGICAL_NAME ViString g 
 "A string containing the logical name you specified when opening the "
 "current IVI session.\n"
 "     You may pass a logical name to the ag3446x_init or "
 "ag3446x_InitWithOptions functions.  The IVI Configuration utility must "
 "contain an entry for the logical name.  The logical name entry refers to a "
 "virtual instrument section in the IVI Configuration file.  The virtual "
 "instrument section specifies a physical device and initial user options.\n"
 "\n"
 "Attribute Value: 1050305"

3 all "I/O Resource Descriptor" AG3446X_ATTR_IO_RESOURCE_DESCRIPTOR ViString g 
 "Indicates the resource descriptor the driver uses to identify the physical "
 "device.\n"
 "    If you initialize the driver with a logical name, this attribute "
 "contains the resource descriptor that corresponds to the entry in the IVI "
 "Configuration utility.  \n"
 "    If you initialize the instrument driver with the resource descriptor, "
 "this attribute contains that value.\n"
 "\n"
 "Attribute Value: 1050304"

3 all "Driver Setup" AG3446X_ATTR_DRIVER_SETUP ViString g 
 "Some cases exist where you must specify instrument driver options at "
 "initialization time.  An example of this is specifying a particular "
 "instrument model from among a family of instruments that the driver "
 "supports.  This is useful when using simulation.  You can specify "
 "driver-specific options through the DriverSetup keyword in the "
 "optionsString parameter to the ag3446x_InitWithOptions function.  If you "
 "open an instrument using a logical name, you can also specify the options "
 "through the IVI Configuration Utility.\n"
 "    The default value is an empty string.\n"
 "\n"
 "Attribute Value: 1050007"

1 all "Basic Operation" 
 "Attributes that control the basic features of the DMM."

2 all "Function" AG3446X_ATTR_FUNCTION ViInt32 gs attrFunctionRangeTable 
 "Specifies the measurement function.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_DC_VOLTS   -  DC Volts\n"
 "AG3446X_VAL_AC_VOLTS   -  AC Volts\n"
 "AG3446X_VAL_DC_CURRENT   -  DC Current\n"
 "AG3446X_VAL_AC_CURRENT   -  AC Current\n"
 "AG3446X_VAL_2_WIRE_RES   -  2 Wire Resistance\n"
 "AG3446X_VAL_4_WIRE_RES   -  4 Wire Resistance\n"
 "AG3446X_VAL_FREQ   -  Frequency\n"
 "AG3446X_VAL_PERIOD   -  Period\n"
 "AG3446X_VAL_TEMPERATURE   -  Temperature\n"
 "AG3446X_VAL_CONTINUITY   -  Continuity\n"
 "AG3446X_VAL_DIODE   -  Diode\n"
 "AG3446X_VAL_DC_VOLTS_RATIO   -  DC Volts Ratio\n"
 "AG3446X_VAL_CAPACITANCE - Capacitance\n"
 "\n"
 "Default Value: AG3446X_VAL_DC_VOLTS\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]FUNCtion[:ON] "
 "\"<function>\"\n"
 "\n"
 "Attribute Value: 1250001"

2 all "Range" AG3446X_ATTR_RANGE ViReal64 gs 
 "Pass the measurement range you want to use.  The driver sets the "
 "AG3446X_ATTR_RANGE attribute to this value.  \n"
 "\n"
 "Use positive values to represent the absolute value of the maximum "
 "expected measurement.  The value must be in units appropriate for the "
 "Measurement Function.  For example, when you set the Measurement Function "
 "to AG3446X_VAL_DC_VOLTS, you must specify the Range in volts.  Setting "
 "this parameter to 10.0 configures the DMM to measure DC voltages from "
 "-10.0 to +10.0 volts.\n"
 "\n"
 "The driver reserves special negative values for controlling the DMM's "
 "auto-ranging capability.\n"
 "\n"
 "Defined Values:\n"
 "AG3446X_VAL_AUTO_RANGE_ON  (-1.0) - Auto-range On\n"
 "AG3446X_VAL_AUTO_RANGE_OFF (-2.0) - Auto-range Off\n"
 "AG3446X_VAL_AUTO_RANGE_ONCE (-3.0) - Auto-range Once\n"
 "    \n"
 "Default Value:\n"
 "AG3446X_VAL_AUTO_RANGE_ON (-1.0)\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Setting this parameter to AG3446X_VAL_AUTO_RANGE_ONCE configures the "
 "DMM to auto-range once, turn auto-range off, and then remain at the "
 "current maximum range.\n"
 "\n"
 "(2) Setting this parameter AG3446X_VAL_AUTO_RANGE_OFF configures the DMM "
 "to stop auto-ranging and keep the range fixed at the current maximum "
 "range.\n"
 "\n"
 "(3) Capacitance applies only to the 34465A, 34470A and EDU34450A.\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:{AC|DC}:RANGe{<range>|MIN|MAX|DEF}\n"
 "[SENSe:]CURRent:{AC|DC}:RANGe:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]{RESistance|FRESistance}:RANGe {<range>|MIN|MAX|DEF}\n"
 "[SENSe:]{RESistance|FRESistance}:RANGe:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]VOLTage:{AC|DC}:RANGe {<range>|MIN|MAX|DEF}\n"
 "[SENSe:]VOLTage:{AC|DC}:RANGe:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]CAPacitance:RANGe:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]CAPacitance:RANGe[:UPPer] {<range>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250002"

2 all "Resolution Absolute" AG3446X_ATTR_RESOLUTION_ABSOLUTE ViReal64 gs 
 "Pass your desired measurement resolution in absolute units. The driver "
 "sets the AG3446X_ATTR_RESOLUTION_ABSOLUTE attribute to this value.\n"
 "\n"
 "Setting this parameter to lower values increases the measurement accuracy. "
 " Setting this parameter to higher values increases the measurement speed.  "
 "    \n"
 "\n"
 "Valid Range:\n"
 "\n"
 "The valid range depends on the current measurement function and the "
 "current measurement range that you select with the AG3446X_ATTR_FUNCTION "
 "and the AG3446X_ATTR_RANGE attributes. The table below shows the minimum "
 "and maximum resolution values for each measurement type. The minimum "
 "resolution values are based on the maximum possible range for that "
 "measurement function. The maximum resolution values are based on the "
 "minimum possible range.\n"
 "\n"
 "Default Value: 1E-6\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) This parameter is ignored if the 'Range' parameter is set to "
 "AG3446X_VAL_AUTO_RANGE_ON.\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent[:DC]:RESolution {<resolution>|MIN|MAX|DEF}\n"
 "[SENSe:]{RESistance|FRESistance}:RESolution {<resolution>|MIN|MAX|DEF}\n"
 "[SENSe:]VOLTage[:DC]:RESolution{<resolution>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250008"

1 all "Trigger" 
 "Attributes that configure the triggering capabilities of the DMM."

2 all "Trigger Source" AG3446X_ATTR_TRIGGER_SOURCE ViInt32 gs 
 "Specify the trigger source you want to use.  The driver sets the\n"
 "AG3446X_ATTR_TRIGGER_SOURCE attribute to this value.\n"
 "\n"
 "After you call either the ag3446x_Read or the ag3446x_Initiate function, "
 "the DMM waits for the trigger you specify in this parameter. After it "
 "receives the trigger, the DMM waits the length of time you specify in the "
 "Trigger Delay parameter.  The DMM then takes a measurement.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_IMMEDIATE     - Immediate. The DMM does not wait\n"
 "for a trigger of any kind.\n"
 "AG3446X_VAL_EXTERNAL      - External. The DMM waits for a\n"
 "trigger on the external trigger input.\n"
 "AG3446X_VAL_SOFTWARE_TRIG - BUS. The DMM waits until you call the "
 "ag3446x_SendSoftwareTrigger function.\n"
 "AG3446X_VAL_INTERNAL      - Internal. Provides level triggering "
 "capability.\n"
 "\n"
 "Default Value: AG3446X_VAL_IMMEDIATE\n"
 "\n"
 "SCPI Command:\n"
 "TRIGger:SOURce {IMMediate|EXTernal|BUS}\n"
 "TRIGger:SOURce {IMMediate|BUS} for EDU344450A.\n"
 "\n"
 "Notes:\n"
 "(1) AG3446X_VAL_INTERNAL applies only to 34465A and 34470A with DIG "
 "option.\n"
 "(2) AG3446X_VAL_INTERNAL and AG3446X_VAL_EXTERNAL not supported for "
 "EDU34450A.\n"
 "\n"
 "Attribute Value: 1250004"

2 all "Trigger Delay" AG3446X_ATTR_TRIGGER_DELAY ViReal64 gs 
 "Pass the value you want to use for the trigger delay.  Express this value "
 "in seconds.  The driver sets the AG3446X_ATTR_TRIGGER_DELAY attribute to "
 "this value. \n"
 "\n"
 "The trigger delay specifies the length of time the DMM waits after it "
 "receives the trigger and before it takes a measurement.\n"
 "\n"
 "Use positive values to set the trigger delay in seconds.  The driver "
 "reserves negative values for configuring the DMM to calculate the trigger "
 "delay automatically.\n"
 "\n"
 "Defined Constant Values:\n"
 "AG3446X_VAL_AUTO_DELAY_OFF (-2.0)- Auto-delay off\n"
 "AG3446X_VAL_AUTO_DELAY_ON (-1.0) - Auto-delay on\n"
 "\n"
 "Valid Manual Range:  0.0 to 3600.0 (seconds)\n"
 " \n"
 "Default Value: 0.0 (seconds)\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Setting this parameter to AG3446X_VAL_AUTO_DELAY_ON (-1.0) configures "
 "the DMM to calculate the trigger delay before each measurement.\n"
 "\n"
 "(2) Setting this parameter to AG3446X_VAL_AUTO_DELAY_OFF (-2.0) stops the "
 "DMM from calculating the trigger delay and sets the trigger delay to the "
 "last automatically calculated value.\n"
 "\n"
 "SCPI Command:\n"
 "TRIGger:DELay {<seconds>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250005"

2 all "Trigger Slope" AG3446X_ATTR_TRIGGER_SLOPE ViInt32 gs attrTriggerSlopeRangeTable 
 "Pass the polarity of the external trigger slope. The driver sets the "
 "AG3446X_ATTR_TRIGGER_SLOPE attribute to this value. The DMM triggers on "
 "either the rising or the falling edge of the external trigger source "
 "depending on the value of this attribute. The driver uses this value to "
 "set the AG3446X_ATTR_TRIGGER_SLOPE attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_POSITIVE   -  Positive. The driver triggers on the rising edge "
 "of the external trigger.\n"
 "AG3446X_VAL_NEGATIVE   -  Negative. The driver triggers on the falling "
 "edge of the external trigger.\n"
 "\n"
 "Default Value: AG3446X_VAL_NEGATIVE\n"
 "\n"
 "SCPI Command:\n"
 "TRIGger:SLOPe {POSitive|NEGative}\n"
 "\n"
 "Attribute Value: 1250334"

2 all "AG3446X_ATTR_TRIGGER_LEVEL" AG3446X_ATTR_TRIGGER_LEVEL ViReal64 gs 
 "Sets the level on which a trigger occurs when level triggering is enabled.\n"
 "\n"
 "Valid Range:\n"
 "For different measurement function and range/input terminals:\n"
 "DCV; 100 mV to 100 V ranges, fixed range: +/-120% of range\n"
 "DCV; 1000 V range, fixed range: +/-1000 V\n"
 "DCV; Auto range: +/-1000 V\n"
 "DCI; 3 A terminals, fixed range: +/-120% of range\n"
 "DCI; 3 A terminals, autorange: +/-3.6 A\n"
 "DCI, 10 A terminals: +/-12 A\n"
 "RESistance/FRESistance; All ranges, fixed range: 0 to +120% of range\n"
 "RESistance/FRESistance; Autorange: 0 to +1.2 GOhm\n"
 "ACV; 100 mV to 100 V ranges, fixed range: 0 to +120% of range\n"
 "ACV; 750 V range, fixed range: 0 to +1000 V\n"
 "ACV; Autorange: 0 to +1000 V\n"
 "ACI; 3 A terminals, fixed range: 0 to +120% of range\n"
 "ACI; 3 A terminals, autorange: 0 to +3.6 A\n"
 "ACI; 10 A terminals: 0 to +12 A\n"
 "Frequency: 3 Hz to 300 kHz\n"
 "Period: 3.33333333 us to 0.333333333 s\n"
 "\n"
 "Default Value: 0\n"
 "\n"
 "SCPI Commands:\n"
 "TRIGger:LEVel {<level>|MIN|MAX|DEF}\n"
 "TRIGger:LEVel? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A, and requires the "
 "DIG option."

1 all "AC Measurements" 
 "Attributes that configure additional parameters for AC volts and AC "
 "current measurements.\n"

2 all "AC Minimum Frequency" AG3446X_ATTR_AC_MIN_FREQ ViReal64 gs attrAcMinFreqRangeTable 
 "Pass the minimum expected frequency component of the input signal in "
 "Hertz. This parameter affects the instrument behavior only when you set "
 "the Measurement Function parameter to AC Measurement. The driver sets the "
 "AG3446X_ATTR_AC_MIN_FREQ attribute to this value. \n"
 "\n"
 "Units: hertz\n"
 "\n"
 "Valid Range:\n"
 "3.0   to  20.0   coerced to  3.0\n"
 "20.0   to  200.0   coerced to  20.0\n"
 "200.0   to  300000.0   coerced to  200.0\n"
 "\n"
 "Default Value: 20.0 \n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:AC:BANDwidth {<filter>|MIN|MAX|DEF}\n"
 "[SENSe:]VOLTage:AC:BANDwidth {<filter>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250006"

2 all "AC Maximum Frequency" AG3446X_ATTR_AC_MAX_FREQ ViReal64 gs attrAcMaxFreqRangeTable 
 "Pass the maximum expected frequency component of the input signal in "
 "Hertz. This parameter affects instrument behavior only when you set the "
 "Measurement Function parameter to AC Measurement. The driver sets the "
 "AG3446X_ATTR_AC_MAX_FREQ attribute to this value. \n"
 "\n"
 "Units: hertz\n"
 "\n"
 "Valid Range:\n"
 "3.0   to  300000.0   coerced to  300000.0\n"
 "\n"
 "Default Value: 300000.0 \n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:AC:BANDwidth {<filter>|MIN|MAX|DEF}\n"
 "[SENSe:]VOLTage:AC:BANDwidth {<filter>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250007"

1 all "Frequency Measurements" 
 "Attributes that configure additional parameters for frequency and period "
 "measurements."

2 all "Frequency Voltage Range" AG3446X_ATTR_FREQ_VOLTAGE_RANGE ViReal64 gs attrFreqVoltageRangeRangeTable 
 "Pass the expected maximum value of the input signal for frequency and "
 "period measurements in volts RMS. The driver sets the "
 "AG3446X_ATTR_FREQ_VOLTAGE_RANGE attribute to this value.  \n"
 "\n"
 "The driver reserves special negative values for the auto-range mode.\n"
 "\n"
 "Defined Values:\n"
 "AG3446X_VAL_AUTO_RANGE_ON  (-1.0) - Auto-range On\n"
 "AG3446X_VAL_AUTO_RANGE_OFF (-2.0) - Auto-range Off\n"
 "AG3446X_VAL_AUTO_RANGE_ONCE(-3.0) - Auto-range once\n"
 "0.0   to  0.1    coerced to  0.1\n"
 "0.1   to  1.0    coerced to  1.0\n"
 "1.0   to  10.0   coerced to  10.0\n"
 "10.0  to  100.0  coerced to  100.0\n"
 "100.0 to  1000.0 coerced to  1000.0\n"
 "\n"
 "Default Value: 10.0 volts RMS\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]{FREQuency|PERiod}:VOLTage:RANGe{<range>|MIN|MAX|DEF}\n"
 "[SENSe:]{FREQuency|PERiod}:VOLTage:RANGe:AUTO{OFF|ON|ONCE}\n"
 "\n"
 "Attribute Value: 1250101"

1 all "Temperature Measurements" 
 "Attribues that configure additional parameters for temperature "
 "measurements."

2 all "Transducer Type" AG3446X_ATTR_TEMP_TRANSDUCER_TYPE ViInt32 gs attrTempTransducerTypeRangeTable 
 "Specifies the transducer probe type to use for temperature measurements of "
 "the DMM.  The driver uses this value to set the "
 "AG3446X_ATTR_TEMP_TRANSDUCER_TYPE attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_2_WIRE_THER  -  2 Wire Thermistor\n"
 "AG3446X_VAL_4_WIRE_THER  -  4 Wire Thermistor\n"
 "AG3446X_VAL_2_WIRE_RTD   -  2 Wire RTD\n"
 "AG3446X_VAL_4_WIRE_RTD   -  4 Wire RTD\n"
 "AG3446X_VAL_THERMOCOUPLE - Thermocouple\n"
 "\n"
 "Default Value: AG3446X_VAL_4_WIRE_RTD\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TYPE {TCouple | THERmistor | FTHermistor | "
 "FRTD | RTD}\n"
 "\n"
 "Attribute Value: 1250201\n"
 "\n"
 "Notes:\n"
 "(1) AG3446X_VAL_THERMOCOUPLE applies only to the 34465A and 34470A."

2 all "Thermocouple" 
 "Attributes for configuring the thermocoulple transducer type."

3 all "Fixed Reference Junction" AG3446X_ATTR_TEMP_TC_FIXED_REF_JUNC ViReal64 gs 
 "Sets the fixed reference junction temperature in degrees Celsius for "
 "thermocouple measurements.\n"
 "\n"
 "Valid Range:\n"
 "-20 to 80 centigrade\n"
 "\n"
 "Default Value:\n"
 "0 centigrade\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction "
 "{<temperature>|MIN|MAX|DEF}]\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction? [{MIN|MAX|DEF}]"

3 all "Reference Junction Type" AG3446X_ATTR_TEMP_TC_REF_JUNC_TYPE ViInt32 gs attrTempTcRefJuncTypeRangeTable 
 "Thermocouple measurements require a reference junction temperature. For "
 "the reference junction temperature, you can use an internal measurement, "
 "or a known fixed junction temperature. \n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_TEMP_REF_JUNC_INTERNAL - Thermocouple Reference Junction "
 "Internal.\n"
 "AG3446X_VAL_REF_JUNC_FIXED- Thermocouple Reference Junction Fixed.\n"
 "\n"
 "Default Value: AG3446X_VAL_TEMP_REF_JUNC_INTERNAL\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction:TYPE {INTernal|FIXed}\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction:TYPE?\n"

3 all "Thermocouple Type" AG3446X_ATTR_TEMP_TC_TYPE ViInt32 gs attrTempTcTypeRangeTable 
 "Selects the thermocouple type for thermocouple measurements.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_TEMP_TC_E - Thermocouple E\n"
 "AG3446X_VAL_TEMP_TC_J - Thermocouple J\n"
 "AG3446X_VAL_TEMP_TC_K - Thermocouple K\n"
 "AG3446X_VAL_TEMP_TC_N - Thermocouple N\n"
 "AG3446X_VAL_TEMP_TC_R - Thermocouple R\n"
 "AG3446X_VAL_TEMP_TC_T - Thermocouple T\n"
 "\n"
 "Default Value: AG3446X_VAL_TEMP_TC_E\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:TYPE {E|J|K|N|R|T}\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:TYPE?"

3 all "AG3446X_ATTR_TEMP_TC_CHECK_ENABLED" AG3446X_ATTR_TEMP_TC_CHECK_ENABLED ViBoolean gs Boolean_values 
 "Disables or enables the thermocouple check feature to verify that your "
 "thermocouples are properly connected for measurements. When enabled, the "
 "instrument measures the resistance after each thermocouple measurement to "
 "ensure a proper connection. If an open connection is detected, the "
 "instrument reports an overload condition.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:CHECk {ON|1|OFF|0}\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:CHECk?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) Enabling the thermocouple check feature slows measurement rates "
 "because two measurements have to be made for each temperature measurement "
 "values produced."

3 all "AG3446X_ATTR_TEMP_TC_REF_JUNC_OFFS_ADJ" AG3446X_ATTR_TEMP_TC_REF_JUNC_OFFS_ADJ ViReal64 gs 
 "Allows you to make minor temperature adjustments to correct for the "
 "differences between the DMM internal temperature measurement of the front "
 "connection and the actual temperature of the measurement terminals.\n"
 "\n"
 "Valid Range:\n"
 "-20 to 20 centigrade\n"
 "\n"
 "Default Value: 0 centigrade\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction:OFFSet:ADJust "
 "{<temperature>|MIN|MAX|DEF}\n"
 "[SENSe:]TEMPerature:TRANsducer:TCouple:RJUNction:OFFSet:ADJust? "
 "[{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and the 34470A.\n"
 "(2) Since the internal reference temperature is the temperature of the "
 "front connections, use of the rear connections with the selection of the "
 "internal reference junction will have an unknown error with no specified "
 "performance and is not recommended."

2 all "Resistance Temperature Device" 
 "Attributes that configure the RTD transducer type."

3 all "RTD Resistance" AG3446X_ATTR_TEMP_RTD_RES ViReal64 gs 
 "Specifies the R0 parameter (resistance) for a resistance temperature "
 "device. The RTD resistance is also known as the RTD reference value. The "
 "driver sets the AG3446X_ATTR_TEMP_RTD_RES attribute to this value.\n"
 "\n"
 "Valid Range: 80.0 to 120.0 ohms\n"
 "\n"
 "Default Value: 100.0 ohms\n"
 "\n"
 "Notes: \n"
 "\n"
 "(1) This attribute affects both 2-wire and 4-wire RTD measurements. \n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:{RTD|FRTD}:RESistance[:REFerence]\n"
 "{<reference>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250242"

3 all "RTD Alpha" AG3446X_ATTR_TEMP_RTD_ALPHA ViReal64 gs 
 "Pass the alpha parameter for a resistance temperature device. The driver "
 "sets the AG3446X_ATTR_TEMP_RTD_ALPHA attribute to this value.\n"
 "\n"
 "Valid Values: \n"
 "This parameter supports only Type 85 RTDs (alpha = 0.00385) for RTD "
 "temperature measurements.\n"
 "\n"
 "Default Value: 85\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) This parameter affects both 2-wire and 4-wire RTD measurements.\n"
 "\n"
 "SCPI Command:\n"
 "TEMP:TRAN:RTD:TYPE\n"
 "\n"
 "Attribute Value: 1250241"

3 all "AG3446X_ATTR_TEMP_TRANSDUCER_OFFSET_COMPENSATE_ENABLED" AG3446X_ATTR_TEMP_TRANSDUCER_OFFSET_COMPENSATE_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables offset compensation for 2-wire and 4-wire RTD "
 "measurements.\n"
 "\n"
 "Offset compensation removes the effects of small dc voltages in the "
 "circuit being measured. The technique involves taking the difference "
 "between two resistance measurements, one with the current source set to "
 "the normal value, and one with the current source set to a lower value.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:{FRTD|RTD}:OCOMpensated {ON|1|OFF|0}\n"
 "[SENSe:]TEMPerature:TRANsducer:{FRTD|RTD}:OCOMpensated?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) This attribute affects both 2-wire and 4-wire resistance measurements."

3 all "AG3446X_ATTR_TEMP_TRANSDUCER_POWER_LIMIT_ENABLED" AG3446X_ATTR_TEMP_TRANSDUCER_POWER_LIMIT_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables low-power, 2-wire or 4-wire, RTD measurements.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:{FRTD|RTD}:POWer:LIMit[:STATe] {ON|1|OFF|0}\n"
 "[SENSe:]TEMPerature:TRANsducer:{FRTD|RTD}:POWer:LIMit[:STATe]?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "Thermistor" 
 "Attributes that configure the thermistor transducer type.\n"

3 all "Thermistor Resistance" AG3446X_ATTR_TEMP_THERMISTOR_RES ViReal64 gs 
 "Pass the resistance of the thermistor in Ohms. The driver sets the "
 "AG3446X_ATTR_TEMP_THERMISTOR_RES attrribute to this value. \n"
 "\n"
 "Valid Range: 5000.0 ohms (Only available choise)\n"
 "\n"
 "Default Value: 5000 ohms\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) The driver assumes that you are using an interchangeable thermistor. "
 "Interchangeable thermistors are thermistors that exhibit similar behavior "
 "for a given resistance value.\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:{THERmistor|FTHermistor}:TYPE 5000\n"
 "For EDU34450A:\n"
 "[SENSe:][PRIMary:]TEMPerature:TRANsducer:THERmistor:TYPE 5000 \n"
 "\n"
 "Attribute Value: 1250251"

3 all "AG3446X_ATTR_TEMP_THERMISTOR_POWER_LIMIT_ENABLED" AG3446X_ATTR_TEMP_THERMISTOR_POWER_LIMIT_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables low-power thermistor measurements (either 2- or "
 "4-wire).\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]TEMPerature:TRANsducer:{FTHermistor|THERmistor}:POWer:LIMit[:STATe"
 "] {ON|1|OFF|0}\n"
 "[SENSe:]TEMPerature:TRANsducer:{FTHermistor|THERmistor}:POWer:LIMit[:STATe"
 "]?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) Only integration times of 1, 10, or 100 PLC provide normal mode (line "
 "frequency noise) rejection."

1 all "MultiPoint Acquisition" 
 "Attributes for acquiring data on multiple triggers and multiple "
 "measurements per trigger.\n"
 "    "

2 all "Trigger Count" AG3446X_ATTR_TRIGGER_COUNT ViInt32 gs 
 "Pass the number of triggers you want the DMM to receive before returning "
 "to the Idle state.  The driver sets the AG3446X_ATTR_TRIGGER_COUNT "
 "attribute to this value.\n"
 "\n"
 "Valid Range:\n"
 "1 to 1000000\n"
 "\n"
 "Default Value: 1\n"
 "\n"
 "SCPI Command:\n"
 "TRIGger:COUNt {<count>|MIN|MAX|DEF|INFinity}\n"
 "\n"
 "Attribute Value: 1250304"

2 all "Sample Count" AG3446X_ATTR_SAMPLE_COUNT ViInt32 gs 
 "Pass the number of measurements you want the DMM to take each time it "
 "receives a trigger.  The driver sets the AG3446X_ATTR_SAMPLE_COUNT "
 "attribute to this value. \n"
 "\n"
 "Valid Range:\n"
 "1 to 1000000 for 34460A and 34461A\n"
 "1 to 1000000000 for 34465A and 34470A\n"
 "\n"
 "Default Value: 1\n"
 "\n"
 "SCPI Command: \n"
 "SAMPle:COUNt {<count>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1250301"

2 all "Sample Trigger" AG3446X_ATTR_SAMPLE_TRIGGER ViInt32 gs attrSampleTriggerRangeTable 
 "Determines sample timing, when the sample count is greater than one.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_IMMEDIATE - Immediate, The first sample starts one trigger "
 "delay time after the trigger, and then the trigger delay time is inserted "
 "between the first and second samples, the second and third, and so on.\n"
 "AG3446X_VAL_TIMER - Timer, The first sample starts one trigger delay time "
 "after the trigger. However, the second sample starts one sample interval "
 "after the start of the first sample, and so on.\n"
 "\n"
 "Default Value: AG3446X_VAL_IMMEDIATE\n"
 "\n"
 "SCPI Commands:\n"
 "SAMPle:SOURce {IMMediate|TIMer}\n"
 "SAMPle:SOURce?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) It is recommended that all triggered measurements be made using an "
 "appropriate fixed manual range.\n"
 "(3) This attribute has no effect if the AG3446X_ATTR_SAMPLE_COUNT is 1.\n"
 "\n"
 "Attribute Value: 1250302"

2 all "Sample Interval" AG3446X_ATTR_SAMPLE_INTERVAL ViReal64 gs 
 "Sets a sample interval for timed sampling (SAMPle:SOURce TIMer) when the "
 "sample count is greater than one.\n"
 "\n"
 "The first sample is taken one trigger delay time after the trigger. The "
 "second sample starts one sample interval after the start of the first "
 "sample, and so forth. Note that the sample timing is determinant because "
 "the start of each sample is determined by the sample interval. Integration "
 "and auto-ranging affect the sampling time for each sample, but not the "
 "sample interval as long as the sample interval is longer than the sampling "
 "time. Periodic sampling continues until the sample count is satisfied.\n"
 "\n"
 "Valid Values(34465A,34470A):\n"
 "0 to 3600 seconds (1 us steps)\n"
 "\n"
 "Valid values(EDU34450A):\n"
 "0.01 to 3600 seconds (100 us steps)\n"
 "\n"
 "Default Value: 1\n"
 "\n"
 "Attribute Value: 1250303\n"
 "\n"
 "SCPI Commands:\n"
 "SAMPle:TIMer {<interval>|MIN|MAX|DEF}\n"
 "SAMPle:TIMer? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A, 34470A, and EDU34450A."

2 all "Meas Complete Destination" AG3446X_ATTR_MEAS_COMPLETE_DEST ViInt32 gs 
 "This instrument does not support the measurement-complete signal. This "
 "function exist only for class compliance.\n"
 "\n"
 "Attribute Value: 1250305"

2 all "AG3446X_ATTR_SAMPLE_COUNT_PRE_TRIGGER" AG3446X_ATTR_SAMPLE_COUNT_PRE_TRIGGER ViInt32 gs 
 "Allows collection of the data being digitized before the trigger. Reserves "
 "memory for pretrigger samples up to the specified number of pretrigger "
 "samples.\n"
 "\n"
 "For example, with a sample count of 50,000, and a pretrigger sample count "
 "of 20,000, up to 20,000 samples are taken before the trigger, then 30,000 "
 "samples are taken after the trigger occurs.\n"
 "The sample count and pretrigger count do not affect when the trigger "
 "occurs. If the memory allocated for pretrigger samples fills up, the "
 "oldest readings are discarded. In the example above, the 20,000 most "
 "recent pretrigger samples are saved, even if more than 20,000 samples "
 "occur before the trigger. If the trigger occurs before the pretrigger "
 "count is satisfied, only the actual pretrigger samples taken are saved.\n"
 "In all cases, after the trigger is received, only sample count minus "
 "specified pretrigger count readings are taken. In this example, if the "
 "trigger occurs after 5 pretrigger samples have been taken (instead of the "
 "specified 20,000), only 30,000 post-trigger samples are taken. This is "
 "because memory was reserved for 20,000 pretrigger samples.\n"
 "\n"
 "Valid Values:\n"
 "0 to 1,999,999\n"
 "\n"
 "Default Value: 0\n"
 "\n"
 "SCPI Commands:\n"
 "SAMPle:COUNt:PRETrigger {<count>|MIN|MAX|DEF}\n"
 "SAMPle:COUNt:PRETrigger? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) Pretrigger applies to all measurement functions except Continuity and "
 "Diode test.\n"
 "(3) If a trigger occurs during a measurement, that measurement is "
 "considered to be a pretrigger sample.\n"
 "(4) After setting the sample count and pretrigger sample count, you must "
 "place the DMM in the "
 "\"waitfor-trigger\" state.\n"
 "(5) The pretrigger sample count must be less than the sample count.\n"
 "(6) If any of the calculation functions are on, the pretrigger count is "
 "limited to 10,000 samples."

1 all "Configuration Information" 
 "Attributes that return information about the current state of the "
 "instrument.\n"

2 all "Aperture Time" AG3446X_ATTR_APERTURE_TIME ViReal64 gs 
 "Returns the value of the Aperture Time attribute. The driver uses this "
 "value to set the AG3446X_ATTR_APERTURE_TIME attribute.\n"
 "The units of this attribute depend on the value of the "
 "AG3446X_ATTR_APERTURE_TIME_UNITS attribute.\n"
 "\n"
 "Valid Range:\n"
 "0.0  to  0.02  coerced to  0.02\n"
 "0.02 to  0.2   coerced to  0.2\n"
 "0.2  to  1.0   coerced to  1.0\n"
 "1.0  to  10.0  coerced to  10.0\n"
 "10.0 to  100.0 coerced to  100.0\n"
 "\n"
 "Default Value: 10\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent[:DC]:NPLC\n"
 "[SENSe:]{RESistance|FRESistance}:NPLC\n"
 "[SENSe:]TEMPerature:NPLC\n"
 "[SENSe:]VOLTage[:DC]:NPLC\n"
 "\n"
 "Attribute Value: 1250321"

2 all "Aperture Time Units" AG3446X_ATTR_APERTURE_TIME_UNITS ViInt32 gs attrApertureTimeUnitsRangeTable 
 "Specifies the value of the Aperture Time Units attribute. The driver uses "
 "this value to set the AG3446X_ATTR_APERTURE_TIME_UNITS attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_SECONDS - Seconds\n"
 "AG3446X_VAL_POWER_LINE_CYCLES - Powerline cycles\n"
 "\n"
 "Attribute Value: 1250322"

2 all "Auto Range Value" AG3446X_ATTR_AUTO_RANGE_VALUE ViReal64 g 
 "Returns the actual range that the DMM is currently using, even while it is "
 "auto-ranging. The driver uses this value to set the "
 "AG3446X_ATTR_AUTO_RANGE_VALUE attribute.\n"
 "\n"
 "The units of the returned value depend on the value of the "
 "AG3446X_ATTR_FUNCTION attribute.\n"
 "\n"
 "Attribute Value: 1250331"

1 all "Measurement Operation Options" 
 "Attributes that configure different measurement operations.\n"
 "     "

2 all "Auto Zero" AG3446X_ATTR_AUTO_ZERO ViInt32 gs attrAutoZeroRangeTable 
 "Specify the auto-zero mode. The driver sets the AG3446X_ATTR_AUTO_ZERO "
 "attribute to this value.\n"
 "\n"
 "When the auto-zero mode is enabled, the DMM internally disconnects the "
 "input signal and takes a Zero Reading. The DMM then subtracts the Zero "
 "Reading from the measurement. This prevents offset voltages present in the "
 "instrument's input circuitry from affecting measurement accuracy.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_AUTO_ZERO_OFF   -  Auto Zero Off. Disables the auto-zero "
 "feature.\n"
 "AG3446X_VAL_AUTO_ZERO_ON   -  Auto Zero On. Configures the DMM to take a "
 "Zero Reading for each measurement. The DMM subtracts the Zero Reading from "
 "the value it measures.\n"
 "AG3446X_VAL_AUTO_ZERO_ONCE   -  Auto Zero Once. Configures the DMM to take "
 "a Zero Reading immediately. The DMM then subtracts this Zero Reading from "
 "all subsequent values it measures.\n"
 "\n"
 "Default Value: AG3446X_VAL_AUTO_ZERO_ON\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent[:DC]:ZERO:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]RESistance:ZERO:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]TEMPerature:ZERO:AUTO {OFF|ON|ONCE}\n"
 "[SENSe:]VOLTage[:DC]:ZERO:AUTO {OFF|ON|ONCE}\n"
 "\n"
 "Attribute Value: 1250332"

1 all "Miscellaneous Attributes" 
 "Additional Attributes."

2 all "AG3446X_ATTR_MODEL" AG3446X_ATTR_MODEL ViInt32 gs attrModel 
 "Specifies the instrument model, including Agilent 34460A and 34461A.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_MODEL_34460A\n"
 "AG3446X_VAL_MODEL_34461A\n"
 "AG3446X_VAL_MODEL_34465A\n"
 "AG3446X_VAL_MODEL_34470A\n"
 "\n"
 "Default Value:\n"
 "AG3446X_VAL_MODEL_34461A\n"
 "\n"
 "Attribute Value: 1150002"

2 all "ID Query Response" AG3446X_ATTR_ID_QUERY_RESPONSE ViString g 
 "Returns the ID Query response string.  The instrument driver gets the "
 "value of this attribute when you pass VI_TRUE for the ID Query parameter "
 "to the ag3446x_init or ag3446x_InitWithOptions function.\n"
 "\n"
 "Attribute Value: 1150001"

2 all "AG3446X_ATTR_CAL_STRING" AG3446X_ATTR_CAL_STRING ViString gs 
 "Stores a message in calibration memory. Common messages include the last "
 "calibration date, calibration due date, or calibration department contact "
 "information. You can perform this query regardless of whether the "
 "instrument is secured. The driver uses this value to set the "
 "AG3446X_ATTR_CAL_STRING attribute.\n"
 "\n"
 "Default Value:\n"
 ""
 "\"\"\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) You must unsecure the instrument to calibrate it or to change the "
 "calibration string or security code.\n"
 "(2) This string may be stored only from the remote interface, but you can "
 "read the message from the front-panel or remote interface.\n"
 "(3) Storing a calibration message overwrites the previous message, and "
 "this setting is non-volatile.\n"
 "\n"
 "SCPI Command:\n"
 "CALibration:STRing"
 "\"<string>\"\n"
 "\n"
 "Attribute Value: 1153003"

2 all "AG3446X_ATTR_CAL_VALUE" AG3446X_ATTR_CAL_VALUE ViReal64 gs 
 "Specifies the value of the applied calibration signal. The driver uses "
 "this value to set the AG3446X_ATTR_CAL_VALUE attribute.\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "SCPI Command:\n"
 "CALibration:VALue<value>\n"
 "\n"
 "Attribute Value: 1153002"

2 all "AG3446X_ATTR_DATA_POINT_COUNT" AG3446X_ATTR_DATA_POINT_COUNT ViInt32 gs 
 "Sets the number of measurements to store in reading memory. The driver "
 "uses this value to set the AG3446X_ATTR_DATA_POINT_COUNT attribute.\n"
 "\n"
 "Valid Range:\n"
 "34460A: 1 to 1,000 readings\n"
 "34461A: 1 to 10,000 readings \n"
 "34465A/70A: 1 to 50,000 readings (without the MEM option), or 1 to "
 "2,000,000 readings (with the MEM option)\n"
 "\n"
 "Default Value: 1\n"
 "\n"
 "SCPI Command:\n"
 "DATA:POINts:EVENt:THReshold<count>\n"
 "\n"
 "Attribute Value: 1152001"

2 all "AG3446X_ATTR_SECURITY_ENABLED" AG3446X_ATTR_SECURITY_ENABLED ViBoolean gs Boolean_values 
 "Unsecures or secures the instrument for calibration. The driver uses this "
 "value to set the AG3446X_ATTR_SECURITY_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) You must unsecure the instrument to calibrate it or to change the "
 "calibration string or security code.\n"
 "(2) Front panel and remote interface calibration share the same code.\n"
 "(3) This setting is non-volatile; it will not be changed by power cycling "
 "or reset.\n"
 "\n"
 "SCPI Command:\n"
 "CALibration:SECure:STATe{ON|1|OFF|0}[, <code>]\n"
 "\n"
 "Attribute Value: 1153001"

2 all "AG3446X_ATTR_AUTO_RECALL_ENABLE" AG3446X_ATTR_AUTO_RECALL_ENABLE ViBoolean gs Boolean_values 
 "Disables or enables the automatic recall of a specific stored instrument "
 "state at power-on. The driver uses this value to set the "
 "AG3446X_ATTR_AUTO_RECALL_ENABLE attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "SCPI Command:\n"
 "MMEMory:STATe:RECall:AUTO {ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1152002"

2 all "AG3446X_ATTR_AVER_ENABLED" AG3446X_ATTR_AVER_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables statistics computation. The driver uses this value to "
 "set the AG3446X_ATTR_AVER_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:AVERage[:STATe]{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154010"

2 all "AG3446X_ATTR_LIMIT_ENABLED" AG3446X_ATTR_LIMIT_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables limit testing. The driver uses this value to set the "
 "AG3446X_ATTR_LIMIT_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:LIMit[:STATe]{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154001"

2 all "AG3446X_ATTR_LOWER_LIMIT" AG3446X_ATTR_LOWER_LIMIT ViReal64 gs 
 "Sets the lower limit. The driver uses this value to set the "
 "AG3446X_ATTR_LOWER_LIMIT attribute.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15   to  -1.0E-15\n"
 "0\n"
 "+1.0E-15   to  +1.0E+15\n"
 "-120% to +120% for EDU34450A\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Do not set the lower limit above the upper limit, even if you are "
 "using only one limit.\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:LIMit:LOWer[:DATA]{<value>|MIN|MAX|DEF}\n"
 "CALCulate:LIMit:LOWer <value>|MIN|MAX for EDU34450A\n"
 "\n"
 "Attribute Value: 1154007"

2 all "AG3446X_ATTR_UPPER_LIMIT" AG3446X_ATTR_UPPER_LIMIT ViReal64 gs 
 "Sets the upper limit. The driver uses this value to set the "
 "AG3446X_ATTR_UPPER_LIMIT attribute.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15   to  -1.0E-15\n"
 "0\n"
 "+1.0E-15   to  +1.0E+15\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Do not set the lower limit above the upper limit, even if you are "
 "using only one limit.\n"
 "(2) For EDU34450A first set the limit math function (CALC:FUNC LIM) and "
 "turn on math operations (CALC:STAT ON) before setting a limit value. \n"
 "\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:LIMit:UPPer[:DATA]{<value>|MIN|MAX|DEF}\n"
 "CALCulate:LIMit:UPPer <value>|MIN|MAX for EDU34450A\n"
 "\n"
 "Attribute Value: 1154008"

2 all "AG3446X_ATTR_SCALE_ENABLED" AG3446X_ATTR_SCALE_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables the scaling function. The driver uses this value to "
 "set the AG3446X_ATTR_SCALE_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:SCALe[:STATe]{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154009"

2 all "AG3446X_ATTR_SCALE_AUTO_REFERENCE" AG3446X_ATTR_SCALE_AUTO_REFERENCE ViBoolean gs Boolean_values 
 "Enables or disables automatic reference selection for the dB scaling "
 "functions. The driver uses this value to set the "
 "AG3446X_ATTR_SCALE_AUTO_REFERENCE attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:SCALe:REFerence:AUTO{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154011"

2 all "AG3446X_ATTR_SCALE_DB_REFERENCE" AG3446X_ATTR_SCALE_DB_REFERENCE ViReal64 gs 
 "Stores a relative value in the multimeter's dB Relative Register. When the "
 "dB function is enabled, this value will be subtracted from the each "
 "voltage measurement after the measurement is converted to dBm. The driver "
 "uses this value to set the AG3446X_ATTR_SCALE_DB_REFERENCE attribute.\n"
 "\n"
 "Units: dBm\n"
 "\n"
 "Valid Range:\n"
 "-200.0   to  200.0\n"
 "-120.0   to  120.0 for EDU34450A\n"
 "\n"
 "Default Value: 0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Specifying a reference value disables automatic reference selection.\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:SCALe:DB:REFerence{<reference>|MIN|MAX|DEF}\n"
 "CALCulate:DB:REFerence <value>|MIN|MAX (for EDU34450A)\n"
 "\n"
 "Attribute Value: 1154014"

2 all "AG3446X_ATTR_SCALE_DBM_REFERENCE" AG3446X_ATTR_SCALE_DBM_REFERENCE ViReal64 gs attrScaleDbmReferenceRangeTable 
 "Selects the reference resistance for converting voltage measurements to "
 "dBm. This reference value affects both the dBm and dB scaling functions. "
 "The driver uses this value to set the AG3446X_ATTR_SCALE_DBM_REFERENCE "
 "attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_50   -  50\n"
 "AG3446X_VAL_75   -  75\n"
 "AG3446X_VAL_93   -  93\n"
 "AG3446X_VAL_110   -  110\n"
 "AG3446X_VAL_124   -  124\n"
 "AG3446X_VAL_125   -  125\n"
 "AG3446X_VAL_135   -  135\n"
 "AG3446X_VAL_150   -  150\n"
 "AG3446X_VAL_250   -  250\n"
 "AG3446X_VAL_300   -  300\n"
 "AG3446X_VAL_500   -  500\n"
 "AG3446X_VAL_600   -  600\n"
 "AG3446X_VAL_800   -  800\n"
 "AG3446X_VAL_900   -  900\n"
 "AG3446X_VAL_1000   -  1000\n"
 "AG3446X_VAL_1200   -  1200\n"
 "AG3446X_VAL_8000   -  8000\n"
 "\n"
 "Default Value: AG3446X_VAL_600\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:SCALe:DBM:REFerence{<reference>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1154013"

2 all "AG3446X_ATTR_SCALE_FUNCTION" AG3446X_ATTR_SCALE_FUNCTION ViInt32 gs 
 "Selects the operation that will be performed by the scaling function. The "
 "driver uses this value to set the AG3446X_ATTR_SCALE_FUNCTION attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_SCALE_FUNC_DB   -  DB. Performs a relative dB computation. The "
 "result will be the difference between the input signal and the stored DB "
 "relative value, with both values converted to dBm (dB = measurement in dBm "
 "- relative value in dBm).\n"
 "AG3446X_VAL_SCALE_FUNC_DBM   -  DBM. Performs a dBM computation. The "
 "result is logarithmic and is based on a calculation of power delivered to "
 "a reference resistance, relative to 1 milliwatt. (dBm = 10 * "
 "log10(measurement 2 / reference resistance / 1 mW)).\n"
 "AG3446X_VAL_SCALE_FUNC_PCT - PCT. Performs a percent change operation. The "
 "result is the percent change of the measurement from the reference value: "
 "Result = ((Measurement ¨C Reference) / Reference) * 100. % scaling applies "
 "to all measurement functions except Ratio, Continuity, and\n"
 "Diode.\n"
 "AG3446X_VAL_SCALE_FUNC_SCAL - Scale. Performs an Mx-B operation. The "
 "result is the measurement multiplied by the gain value M minus the offset "
 "value B . Mx-B scaling applies to all measurement functions except Ratio, "
 "Continuity, and Diode.\n"
 "\n"
 "Default Value: AG3446X_VAL_SCALE_FUNC_DB\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:SCALe:FUNCtion{DB|DBM|PCT|SCALe}\n"
 "\n"
 "Attribute Value: 1154012\n"
 "\n"
 "Notes:\n"
 "(1) The PCT and SCALe functions apply only to the 34465A and 34470A."

2 all "AG3446X_ATTR_SCALE_GAIN" AG3446X_ATTR_SCALE_GAIN ViReal64 gs 
 "Stores a gain value M for the scaling function.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15 to -1.0E-15, 0.0, +1.0E-15 to 1.0E+15\n"
 "\n"
 "Default Value: 1.0\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SCALe:GAIN {<gain>|MIN|MAX|DEF}\n"
 "CALCulate:SCALe:GAIN? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_SCALE_OFFSET" AG3446X_ATTR_SCALE_OFFSET ViReal64 gs 
 "Stores an offset value B for the scaling function.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15 to -1.0E-15, 0.0, +1.0E-15 to 1.0E+15\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SCALe:OFFSet {<offset>|MIN|MAX|DEF}\n"
 "CALCulate:SCALe:OFFSet? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_SCALE_REFERENCE" AG3446X_ATTR_SCALE_REFERENCE ViReal64 gs 
 "Stores a reference value for the PCT function.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15 to -1.0E-15, 0.0, +1.0E-15 to 1.0E+15\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SCALe:REFerence {<reference>|MIN|MAX|DEF}\n"
 "CALCulate:SCALe:REFerence? [{MIN|MAX|DEF}]\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_SCALE_UNIT" AG3446X_ATTR_SCALE_UNIT ViString gs 
 "Specifies the custom label of up to four characters (for example, RPM) for "
 "scaled measurements.\n"
 "\n"
 "Valid Values:\n"
 "ASCII string of up to four characters\n"
 "\n"
 "Default Value: "
 "\"\"\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SCALe:UNIT <quoted_string>\n"
 "CALCulate:SCALe:UNIT?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_SCALE_UNIT_ENABLED" AG3446X_ATTR_SCALE_UNIT_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables displaying the unit string with measurements on the "
 "front panel when the scaling function is enabled.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SCALe:UNIT:STATe {OFF|ON}\n"
 "CALCulate:SCALe:UNIT:STATe?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_HIST_ENABLED" AG3446X_ATTR_HIST_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables histogram computation. The driver uses this value to "
 "set the AG3446X_ATTR_HIST_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:TRANsform:HISTogram[:STATe]{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154004"

2 all "AG3446X_ATTR_HIST_AUTO_RANGE" AG3446X_ATTR_HIST_AUTO_RANGE ViBoolean gs Boolean_values 
 "Enables or disables automatic selection of the histogram's lower and upper "
 "range values. The driver uses this value to set the "
 "AG3446X_ATTR_HIST_AUTO_RANGE attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Setting the lower or upper range value disables automatic selection of "
 "the lower and upper range values.\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:TRANsform:HISTogram:RANGe:AUTO{ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1154005"

2 all "AG3446X_ATTR_HIST_LOWER_RANGE" AG3446X_ATTR_HIST_LOWER_RANGE ViReal64 gs 
 "Sets the lower range value for the histogram. The driver uses this value "
 "to set the AG3446X_ATTR_HIST_LOWER_RANGE attribute.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15   to  -1.0E-15\n"
 "0.0\n"
 "1.0E-15   to  1.0E+15\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Setting the lower or upper range value disables automatic selection of "
 "the lower and upper range.\n"
 "(2) Do not set the lower range above the upper range, even if you are "
 "using only one range.\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:TRANsform:HISTogram:RANGe:LOWer {<value>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1154002"

2 all "AG3446X_ATTR_HIST_UPPER_RANGE" AG3446X_ATTR_HIST_UPPER_RANGE ViReal64 gs 
 "Sets the upper range value for the histogram. The driver uses this value "
 "to set the AG3446X_ATTR_HIST_UPPER_RANGE attribute.\n"
 "\n"
 "Valid Range:\n"
 "-1.0E+15   to  -1.0E-15\n"
 "0.0\n"
 "1.0E-15   to  1.0E+15\n"
 "\n"
 "Default Value: 0.0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Setting the lower or upper range value disables automatic selection of "
 "the lower and upper range.\n"
 "(2) Do not set the upper range below the lower range, even if you are "
 "using only one range.\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:TRANsform:HISTogram:RANGe:UPPer {<value>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1154003"

2 all "AG3446X_ATTR_HIST_POINT" AG3446X_ATTR_HIST_POINT ViInt32 gs attrHistPointRangeTable 
 "Sets the number of bins between the lower and upper range values for the "
 "histogram. Two additional bins always exist: one for measurements below "
 "the lower range and one for measurements above the upper range. The driver "
 "uses this value to set the AG3446X_ATTR_HIST_POINT attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_10   -  10\n"
 "AG3446X_VAL_20   -  20\n"
 "AG3446X_VAL_40   -  40\n"
 "AG3446X_VAL_100   -  100\n"
 "AG3446X_VAL_200   -  200\n"
 "AG3446X_VAL_400   -  400\n"
 "\n"
 "Default Value: AG3446X_VAL_100\n"
 "\n"
 "SCPI Command:\n"
 "CALCulate:TRANsform:HISTogram:POINts{<value>|MIN|MAX|DEF}\n"
 "\n"
 "Attribute Value: 1154006"

2 all "AG3446X_ATTR_CURR_TERMINAL" AG3446X_ATTR_CURR_TERMINAL ViInt32 gs attrCurrentTerminalRangeTable 
 "Configures the AC or DC current measurement to measure the source on the 3 "
 "A or 10 A terminals. The driver uses this value to set the "
 "AG3446X_ATTR_CURR_TERMINAL attribute. This attribute is only valid to AC "
 "and DC current measurement.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_CURR_TERM_3   -  3\n"
 "AG3446X_VAL_CURR_TERM_10   -  10\n"
 "\n"
 "Default Value: 3\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) 10 A terminal is not available on the 34460A.\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:{AC|DC}:TERMinals {3|10}\n"
 "\n"
 "Attribute Value: 1151002"

2 all "AG3446X_ATTR_VOLT_AUTO_IMPEDANCE" AG3446X_ATTR_VOLT_AUTO_IMPEDANCE ViBoolean gs Boolean_values 
 "Disables or enables automatic input impedance mode for DC voltage and "
 "ratio measurements. The driver uses this value to set the "
 "AG3446X_ATTR_VOLTAGE_AUTO_IMPEDANCE attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable. The input impedance for DC voltage measurements varies "
 "by range\n"
 "VI_FALSE - Disable. The input impedance for DC voltage measurements is "
 "fixed at 10M ohm for all ranges to minimize noise pickup.\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]VOLTage[:DC]:IMPedance:AUTO {ON|1|OFF|0}\n"
 "\n"
 "Attribute Value: 1151001"

2 all "AG3446X_ATTR_CONF_MEAS" AG3446X_ATTR_CONF_MEAS ViInt32 gs attrConfMeasRangeTable 
 "Specifies the measurement type to configure. The driver uses this value to "
 "set the AG3446X_ATTR_CONF_MEAS attribute.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_CONF_MEAS_CONT   -  Continuity\n"
 "AG3446X_VAL_CONF_MEAS_AC_CURRENT   -  AC Current\n"
 "AG3446X_VAL_CONF_MEAS_DC_CURRENT   -  DC Current\n"
 "AG3446X_VAL_CONF_MEAS_DIODE   -  Diode\n"
 "AG3446X_VAL_CONF_MEAS_FREQ   -  Frequency\n"
 "AG3446X_VAL_CONF_MEAS_PER   -  Period\n"
 "AG3446X_VAL_CONF_MEAS_RES   -  2 Wire Resistance\n"
 "AG3446X_VAL_CONF_MEAS_FRES   -  4 Wire Resistance\n"
 "AG3446X_VAL_CONF_MEAS_TEMP   -  Temperature\n"
 "AG3446X_VAL_CONF_MEAS_AC_VOLTAGE   -  AC Voltage\n"
 "AG3446X_VAL_CONF_MEAS_DC_VOLTAGE   -  DC Voltage\n"
 "AG3446X_VAL_CONF_MEAS_DC_VOLTAGE_RATIO   -  DC Voltage Ratio\n"
 "AG3446X_VAL_CONF_MEAS_CAP - Capacitance\n"
 "\n"
 "Default Value: AG3446X_VAL_CONF_MEAS_CONT\n"
 "\n"
 "SCPI Command:\n"
 "CONFigure:CONTinuity\n"
 "CONFigure:CURRent:{AC|DC}\n"
 "CONFigure:DIODe\n"
 "CONFigure:{FREQuency|PERiod}\n"
 "CONFigure:{RESistance|FRESistance}\n"
 "CONFigure:TEMPerature\n"
 "CONFigure[:VOLTage]:{AC|DC}\n"
 "CONFigure[:VOLTage][:DC]:RATio\n"
 "CONFigure:CAPacitance\n"
 "\n"
 "Attribute Value: 1155001\n"
 "\n"
 "Notes:\n"
 "(1) AG3446X_VAL_CONF_MEAS_CAP applies only to the 34465A, 34470A and "
 "EDU34450A.\n"
 "(2) AG3446X_VAL_CONF_MEAS_DC_VOLTAGE_RATIO\n"
 "    AG3446X_VAL_CONF_MEAS_PER\n"
 "are not supported for EDU34450A."

2 all "AG3446X_ATTR_NULL_ENABLED" AG3446X_ATTR_NULL_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables the null function for each measurements. The driver "
 "uses this value to set the AG3446X_ATTR_NULL_ENABLED attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:{AC|DC}:NULL[:STATe]\n"
 "[SENSe:]{FREQuency|PERiod}:NULL[:STATe]\n"
 "[SENSe:]{RESistance|FRESistance}:NULL[:STATe]\n"
 "[SENSe:]TEMPerature:NULL[:STATe]\n"
 "[SENSe:]VOLTage:{AC|DC}:NULL[:STATe]\n"
 "[SENSe:]CAPacitance:NULL[:STATe]\n"
 "\n"
 "Attribute Value: 1151005\n"
 "\n"
 "Notes:\n"
 "(1) Capacitance applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_NULL_AUTO_ENABLED" AG3446X_ATTR_NULL_AUTO_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables automatic null value selection for each measurement. "
 "The driver uses this value to set the AG3446X_ATTR_NULL_AUTO_ENABLED "
 "attribute.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:{AC|DC}:NULL:VALue:AUTO\n"
 "[SENSe:]{FREQuency|PERiod}:NULL:VALue\n"
 "[SENSe:]{RESistance|FRESistance}:NULL:VALue:AUTO\n"
 "[SENSe:]TEMPerature:NULL:VALue:AUTO\n"
 "[SENSe:]VOLTage:{AC|DC}:NULL:VALue:AUTO\n"
 "[SENSe:]CAPacitance:NULL:VALue:AUTO\n"
 "\n"
 "Attribute Value: 1151003\n"
 "\n"
 "Notes:\n"
 "(1) Capacitance applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_NULL_VALUE" AG3446X_ATTR_NULL_VALUE ViReal64 gs 
 "Stores a null value for each measurements. The driver uses this value to "
 "set the AG3446X_ATTR_NULL_VALUE attribute.\n"
 "\n"
 "Valid Range:\n"
 "-12A   to  12A  for current\n"
 "-1.2E6  to 1.2E6 for frequency and period\n"
 "-1.2E8  to 1.2E8 for resistance\n"
 "-1.0E15  to  1.0E15 for temperature\n"
 "-1200  to  1200 for voltage\n"
 "-120 to 120 for capacitance\n"
 "\n"
 "Default Value: 0\n"
 "\n"
 "Notes:\n"
 "\n"
 "(1) Specifying a null value disables automatic null value selection\n"
 "(2) To use the null value, the null state must be on\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]VOLTage:{AC|DC}:NULL:VALue\n"
 "[SENSe:]CURRent:{AC|DC}:NULL:VALue\n"
 "[SENSe:]{FREQuency|PERiod}:NULL:VALue\n"
 "[SENSe:]{RESistance|FRESistance}:NULL:VALue\n"
 "[SENSe:]TEMPerature:NULL:VALue\n"
 "[SENSe:]CAPacitance:NULL:VALue\n"
 "\n"
 "Attribute Value: 1151004\n"
 "\n"
 "Notes:\n"
 "(1) Capacitance applies to the 34465A and 34470A."

2 all "AG3446X_ATTR_SMOOTHING_RESPONSE" AG3446X_ATTR_SMOOTHING_RESPONSE ViInt32 gs attrSmoothingResponseRangeTable 
 "Selects the number of measurements to be averaged by the moving average "
 "(boxcar) filter.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_SMOOTHING_RESPONSE_SLOW - Slow, 100 measurements.\n"
 "AG3446X_VAL_SMOOTHING_RESPONSE_MEDIUM - Medium, 50 measurements. "
 "AG3446X_VAL_SMOOTHING_RESPONSE_FAST - Fast, 10 measurements. \n"
 "\n"
 "Default Value: AG3446X_VAL_SMOOTHING_RESPONSE_FAST\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SMOothing:RESPonse {SLOW|MEDium|FAST}\n"
 "CALCulate:SMOothing:RESPonse?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) The smoothing (moving average) filter is reset when the measurement "
 "function changes, or if a reading is too far beyond the current average."

2 all "AG3446X_ATTR_SMOOTHING_ENABLED" AG3446X_ATTR_SMOOTHING_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables a smoothing (moving average) filter on the "
 "measurements. Smoothing is intended to average out small variations in the "
 "measurements. Larger variations will cause the filter to reset.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:SMOothing[:STATe] {OFF|ON}\n"
 "CALCulate:SMOothing[:STATe]?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) The Calculate subsystem and the individual calculate functions are "
 "disabled for timestamp measurements."

2 all "AG3446X_ATTR_TREND_CHART_ENABLED" AG3446X_ATTR_TREND_CHART_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables trend chart data when controlling the instrument from "
 "remote.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Commands:\n"
 "CALCulate:TCHart[:STATe] {ON|1|OFF|0}\n"
 "CALCulate:TCHart[:STATe]?\n"
 "\n"
 "Notes:\n"
 "(1) You must enable this (ON) before sending INIT or READ? to see trend "
 "chart data when controlling the instrument from remote. If it is disabled "
 "or enabled after INIT or READ?, viewing the trend chart results in a chart "
 "with no data.\n"
 "(2) Trend chart data must be disabled (OFF) to make measurements at the "
 "highest speed (50 kHz)."

2 all "AG3446X_ATTR_MEM_FORM_READING_SEPARATOR" AG3446X_ATTR_MEM_FORM_READING_SEPARATOR ViInt32 gs attrMemFormReadingSeparatorRangeTable 
 "Specifies the character used to separate the columns in stored data.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_SEPARATOR_COM - Comma.\n"
 "AG3446X_VAL_SEPARATOR_SEM - Semicolon.\n"
 "AG3446X_VAL_SEPARATOR_TAB - Tab.\n"
 "\n"
 "Default Value: AG3446X_VAL_SEPARATOR_COM\n"
 "\n"
 "SCPI Commands:\n"
 "MMEMory:FORMat:READing:CSEParator {COMMa|SEMicolon|TAB}\n"
 "MMEMory:FORMat:READing:CSEParator?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_MEM_FORM_READING_INFO_ENABLED" AG3446X_ATTR_MEM_FORM_READING_INFO_ENABLED ViBoolean gs Boolean_values 
 "Disables/enables header information and reading numbers in stored data.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "MMEMory:FORMat:READing:INFormation {OFF|ON}\n"
 "MMEMory:FORMat:READing:INFormation?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_MEM_FORM_ROW_LIMIT_ENABLED" AG3446X_ATTR_MEM_FORM_ROW_LIMIT_ENABLED ViBoolean gs Boolean_values 
 "When enabled, limits the maximum number rows per stored .csv data file to "
 "one million, including any header row, if enabled.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_TRUE\n"
 "\n"
 "SCPI Command:\n"
 "MMEMory:FORMat:READing:RLIMit {OFF|ON}\n"
 "MMEMory:FORMat:READing:RLIMit?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A."

2 all "AG3446X_ATTR_OFFSET_COMPENSATE_ENABLED" AG3446X_ATTR_OFFSET_COMPENSATE_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables offset compensation. Offset compensation removes the "
 "effects of small dc voltages in the circuit being measured. The technique "
 "involves taking the difference between two resistance measurements, one "
 "with the current source set to the normal value, and one with the current "
 "source set to a lower value. Enabling Offset Compensation approximately "
 "doubles the reading time.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]{RESistance|FRESistance}:OCOMpensated {OFF|ON}\n"
 "[SENSe:]{RESistance|FRESistance}:OCOMpensated?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) This attribute affects both 2-wire and 4-wire resistance measurements."

2 all "AG3446X_ATTR_POWER_LIMIT_ENABLED" AG3446X_ATTR_POWER_LIMIT_ENABLED ViBoolean gs Boolean_values 
 "Enables or disables low-power resistance measurements (either 2- or "
 "4-wire).\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]{RESistance|FRESistance}:POWer:LIMit[:STATe] {OFF|ON}\n"
 "[SENSe:]{RESistance|FRESistance}:POWer:LIMit[:STATe]?\n"
 "\n"
 "Notes:\n"
 "(1) This attribute applies only to the 34465A and 34470A.\n"
 "(2) Low-power resistance measurements apply to the 100ohm through 100kohm "
 "ranges only. The 1 Mohm through 1 Gohm ranges source the same current "
 "regardless of the low-power setting."

2 all "Freq Auto Timeout Enabled" AG3446X_ATTR_FREQ_AUTO_TIMEOUT_ENABLED ViBoolean gs Boolean_values 
 "Controls how long the instrument waits before timing out on a frequency or "
 "period measurement when no signal is present.\n"
 "\n"
 "Valid Values:\n"
 "VI_TRUE  - Enable\n"
 "VI_FALSE - Disable\n"
 "\n"
 "Default Value: VI_FALSE\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]FREQuency:TIMeout:AUTO {OFF | ON}"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION" AG3446X_ATTR_SECONDARY_FUNCTION ViInt32 gs 
 "Selects the secondary measurement function for the current selected "
 "measurement specified by the AG3446X_ATTR_FUNCTION attribute.\n"
 "\n"
 "Valid Values:\n"
 "For all measurement functions:\n"
 "    AG3446X_VAL_SEC_FUNC_OFF - Off\n"
 "    AG3446X_VAL_SEC_FUNC_CALC - Calculate data\n"
 "\n"
 "When primary function is AG3446X_VAL_DC_VOLTS\n"
 "    AG3446X_VAL_SEC_FUNC_VAC - AC voltage\n"
 "    AG3446X_VAL_SEC_FUNC_PTP - Peak to Peak\n"
 "\n"
 "When primary function is AG3446X_VAL_AC_VOLTS: \n"
 "    AG3446X_VAL_SEC_FUNC_VDC - DC voltage\n"
 "    \n"
 "When primary function is AG3446X_VAL_DC_CURRENT: \n"
 "    AG3446X_VAL_SEC_FUNC_CAC - AC current\n"
 "    AG3446X_VAL_SEC_FUNC_PTP - Peak to Peak\n"
 "   \n"
 "When primary function is AG3446X_VAL_AC_CURRENT: \n"
 "    AG3446X_VAL_SEC_FUNC_CDC - DC current \n"
 "    AG3446X_VAL_SEC_FUNC_FREQ - Frequency\n"
 "                  \n"
 "When primary function is AG3446X_VAL_FREQ:       \n"
 "    AG3446X_VAL_SEC_FUNC_VAC - AC voltage\n"
 "    AG3446X_VAL_SEC_FUNC_PER - Period\n"
 "             \n"
 "When primary function is AG3446X_VAL_PERIOD:       \n"
 "    AG3446X_VAL_SEC_FUNC_VAC - AC voltage\n"
 "    AG3446X_VAL_SEC_FUNC_FREQ - Frequency\n"
 "  \n"
 "When primary function is AG3446X_VAL_TEMPERATURE or "
 "AG3446X_VAL_DC_VOLTS_RATIO:  \n"
 "    AG3446X_VAL_SEC_FUNC_SENS - Sense data\n"
 "\n"
 "Default Value: AG3446X_VAL_SEC_FUNC_OFF\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]VOLTage[:DC]:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"VOLTage:AC\"|"
 "\"PTPeak\"}\n"
 "[SENSe:]VOLTage:AC:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"FREQuency\"|"
 "\"VOLTage[:DC]\"}\n"
 "[SENSe:]CURRent[:DC]:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"CURRent:AC\"|"
 "\"PTPeak\"}\n"
 "[SENSe:]CURRent:AC:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"FREQuency\"|"
 "\"CURRent[:DC]\"}\n"
 "[SENSe:]FREQuency:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"PERiod\"|"
 "\"VOLTage:AC\"}\n"
 "[SENSe:]PERiod:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"FREQuency\"|"
 "\"VOLTage:AC\"}\n"
 "[SENSe:]{FRESistance|RESistance}:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"}\n"
 "[SENSe:]TEMPerature:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"SENSe:DATA\"}\n"
 "[SENSe:]VOLTage[:DC]:RATio:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"|"
 "\"SENSe:DATA\"}\n"
 "[SENSe:]CAPacitance:SECondary {"
 "\"OFF\"|"
 "\"CALCulate:DATA\"}"

2 all "Range Change Mode" AG3446X_ATTR_RANGE_CHANGE_MODE ViInt32 gs attrRangeChangeModeRangeTable 
 "Selects the fast or continuous range change mode for AC and DC current "
 "measurements.\n"
 "\n"
 "Valid Values:\n"
 "AG3446X_VAL_RANGE_CHANGE_FAST - Fast.\n"
 "AG3446X_VAL_RANGE_CHANGE_CONT- Continuous.\n"
 "\n"
 "Default Value:\n"
 "AG3446X_VAL_RANGE_CHANGE_CONT\n"
 "\n"
 "SCPI Command:\n"
 "[SENSe:]CURRent:SWITch:MODE {FAST | CONTinuous}\n"
 "\n"
 "Notes:\n"
 "(1) This attribute only applies to the 34465A and 34470A.\n"
 "(2) This attribute applies to the 3A current terminals only."

1 all "Hidden Attributes (not user-viewable)" 
 "    "

2 all "AG3446X_ATTR_APERTURE_TIME_SECONDS" AG3446X_ATTR_APERTURE_TIME_SECONDS ViReal64 hidden 
 "This hidden attribute sets/gets the value of the Aperture Time attribute "
 "in seconds."

2 all "AG3446X_ATTR_APERTURE_TIME_NPLC" AG3446X_ATTR_APERTURE_TIME_NPLC ViReal64 hidden 
 "This hidden attribute sets/gets the value of the Aperture Time attribute "
 "in power line cycles."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_TEMP" AG3446X_ATTR_TRIGGER_LEVEL_TEMP ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for temperature measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_PER" AG3446X_ATTR_TRIGGER_LEVEL_PER ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for period measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_FREQ" AG3446X_ATTR_TRIGGER_LEVEL_FREQ ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for frequency measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_RES" AG3446X_ATTR_TRIGGER_LEVEL_RES ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for 2-wire resistance and 4-wire resistance "
 "measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_ACI" AG3446X_ATTR_TRIGGER_LEVEL_ACI ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for AC Current measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_DCI" AG3446X_ATTR_TRIGGER_LEVEL_DCI ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for DC Current measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_ACV" AG3446X_ATTR_TRIGGER_LEVEL_ACV ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for AC Volts measurement."

2 all "AG3446X_ATTR_TRIGGER_LEVEL_DCV" AG3446X_ATTR_TRIGGER_LEVEL_DCV ViReal64 hidden 
 "This hidden attribute sets the level on which a trigger occurs when level "
 "triggering is enabled for DC Volts measurement."

2 all "Option" AG3446X_ATTR_OPTION ViInt32 hidden 
 "This hidden attribute returns the installed options.\n"
 "\n"
 "Valid options are:\n"
 "34460A: GPB, LAN, SEC\n"
 "34461A: GPB, SEC\n"
 "34465A/70A: GPB, SEC, DIG, MEM\n"
 "\n"
 "Valid Values:\n"
 "0 to 31\n"
 "Each bit of the value stands for the status of an option. Options are "
 "defined as follows (from LSB to MSB):\n"
 "AG3446X_VAL_OPT_GPB  -  GPIB interface module\n"
 "AG3446X_VAL_OPT_LAN  -  Enable rear panel LAN/LXI web interface, external "
 "triggering for 34460A\n"
 "AG3446X_VAL_OPT_SEC  -  NISPOM and file security for Truevolt series "
 "DMMslicense.\n"
 "AG3446X_VAL_OPT_DIG  -  Digitizing and advanced triggering for 34465A and "
 "34470A Truevolt DMMs license\n"
 "AG3446X_VAL_OPT_MEM  -  2 MB memory for 34465A and 34470A Truevolt DMMs "
 "license  \n"
 "\n"
 "Default Value: 0"

2 all "CALC_FUNC_ENABLED" AG3446X_ATTR_CALC_FUNC_ENABLED ViBoolean hidden Boolean_values 
 "This hidden attribute returns true if any of the calculation functions are "
 "enabled, returns false if non of the calculation functions are enabled. "
 "Calculation function state attributes includes:\n"
 "    AG3446X_ATTR_SMOOTHING_ENABLED\n"
 "    AG3446X_ATTR_SCALE_ENABLED\n"
 "    AG3446X_ATTR_AVER_ENABLED\n"
 "    AG3446X_ATTR_LIMIT_ENABLED\n"
 "    AG3446X_ATTR_HIST_ENABLED"

2 all "SAMPLE_INTERVAL_MIN" AG3446X_ATTR_SAMPLE_INTERVAL_MIN ViReal64 hidden 
 "This hidden attribute determines the absolute minimum value for the "
 "present configuration of the AG3446X_ATTR_SAMPLE_INTERVAL attribute.\n"
 "\n"
 "To determine the absolute minimum value for the present configuration, set "
 "the sample time to 20 us\n"
 "(which may generate a settings conflict error), then read back the current "
 "sample timer value using the\n"
 "SAMPle:TIMer? query. The sample source must be set to timer with a sample "
 "count or trigger count\n"
 "greater than 1, for the settings conflict error to occur. The settings "
 "conflict error causes the timer to be\n"
 "set to the absolute minimum value."

2 all "OPC Callback Timeout" AG3446X_ATTR_OPC_TIMEOUT ViInt32 hidden 
 "This attribute is hidden.  The driver uses this attribute internally to "
 "set the timeout for the OPC callback.\n"
 "    "

2 all "Resolution" AG3446X_ATTR_RESOLUTION ViReal64 hidden 
 "This hidden attribute sets/gets the resolution factor."

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_VDC" AG3446X_ATTR_SECONDARY_FUNCTION_VDC ViInt32 hidden attrSecFuncVdcRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "DC voltage measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_VAC" AG3446X_ATTR_SECONDARY_FUNCTION_VAC ViInt32 hidden attrSecFuncVacRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "AC voltage measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_CDC" AG3446X_ATTR_SECONDARY_FUNCTION_CDC ViInt32 hidden attrSecFuncCdcRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "DC current measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_CAC" AG3446X_ATTR_SECONDARY_FUNCTION_CAC ViInt32 hidden attrSecFuncCacRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "AC current measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_FREQ" AG3446X_ATTR_SECONDARY_FUNCTION_FREQ ViInt32 hidden attrSecFuncFreqRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "frequency measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_PER" AG3446X_ATTR_SECONDARY_FUNCTION_PER ViInt32 hidden attrSecFuncPerRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "period measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_RES" AG3446X_ATTR_SECONDARY_FUNCTION_RES ViInt32 hidden attrSecFuncResRangeTable 
 "This hidden attribute selects the secondary measurement function for both "
 "2-wire and 4-wire resistance measurements.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_TEMP" AG3446X_ATTR_SECONDARY_FUNCTION_TEMP ViInt32 hidden attrSecFuncTempRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "temperature measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_DC_RATIO" AG3446X_ATTR_SECONDARY_FUNCTION_DC_RATIO ViInt32 hidden attrSecFuncDcRatioRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "DC ratio measurement.\n"

2 all "AG3446X_ATTR_SECONDARY_FUNCTION_CAP" AG3446X_ATTR_SECONDARY_FUNCTION_CAP ViInt32 hidden attrSecFuncCapacitanceRangeTable 
 "This hidden attribute selects the secondary measurement function for the "
 "capacitance measurement.\n"

